// js/api_client.js
// TDD 参考: 5.1, 5.2, 4.2
import { CONFIG } from './config.js';
import {
    state,
    pushBounded,
    DEBUG_LOG_CAPS,
    computeDimensionPathRowStates,
    formatStrictRuntimeReason,
    updateRecognitionCapabilitiesFromPayload,
} from './state.js';
import { REVIEW_CANDIDATES_ROOT_KEY } from './review_candidates_v1.js';
import {
    VECTOR_DEBUG_MAX_WORKSPACE_OVERLAYS,
    VECTOR_DEBUG_MAX_WORKSPACE_PAGES,
    VECTOR_LAYER_DEBUG_MAX_PAGE_OVERLAYS,
} from './vector_layer_debug_v1.js';
import {
    TransportError,
    normalizeTransportError,
    prepareJsonBase64Body,
    readResponsePayload,
} from './legacy_pdf_transport.js';
// ── URL 常量（唯一来源：config.js，此文件无任何硬编码 IP）────────────────────
const ANALYZE_URL       = CONFIG.API_BASE_URL + '/analyze';
const ANALYZE_STAMP_URL = CONFIG.API_BASE_URL + '/analyze_stamp';
const EXPORT_URL        = CONFIG.API_BASE_URL + '/export';
const IMPORT_MEASUREMENTS_URL = CONFIG.API_BASE_URL + '/import_measurements';
const IMPORT_LEGACY_STAMPS_URL = CONFIG.API_BASE_URL + '/import_legacy_stamps';
const STARTUP_LOG_URL   = CONFIG.API_BASE_URL + '/startup_log';
const RUNTIME_STATS_URL = CONFIG.API_BASE_URL + '/runtime_stats';

// 把当前识别选项整理成 /analyze 的 settings 字段（Phase 1：尺寸主识别轴）
export function createVectorDebugRequestBudget() {
    let allocatedPages = 0;
    let remainingOverlays = VECTOR_DEBUG_MAX_WORKSPACE_OVERLAYS;
    return Object.freeze({
        take() {
            if (allocatedPages >= VECTOR_DEBUG_MAX_WORKSPACE_PAGES) {
                return Object.freeze({ enabled: false, overlayLimit: 0 });
            }
            allocatedPages += 1;
            const overlayLimit = Math.min(
                VECTOR_LAYER_DEBUG_MAX_PAGE_OVERLAYS,
                remainingOverlays,
            );
            remainingOverlays -= overlayLimit;
            return Object.freeze({ enabled: true, overlayLimit });
        },
    });
}

export function buildAnalyzeSettingsPayload({ vectorDebugRequest } = {}) {
    const isVectorOnly = state.recognitionSettings.dimension_path === 'vector_only';
    const payload = {
        dimension_path: state.recognitionSettings.dimension_path,
        // Strict backend contract has no view-seg fallback. Keep the user's
        // compatible-mode preference in state, but never send a known-invalid
        // watershed/minesweeper choice on a vector_only request.
        view_seg: isVectorOnly ? 'yolo' : state.recognitionSettings.view_seg,
        gdt_backend: state.recognitionSettings.gdt_backend,
    };
    if (!isVectorOnly) {
        payload.ocr_engine = state.recognitionSettings.ocr_engine;
    }
    // 分层矢量诊断是显式、会话级 opt-in。关闭时连请求键都不存在，
    // 以保持现有 /analyze 请求合同不变；后端仍必须把它当旁路诊断。
    const requestEnabled = vectorDebugRequest === undefined
        || vectorDebugRequest?.enabled === true;
    const requestedOverlayLimit = vectorDebugRequest === undefined
        ? VECTOR_LAYER_DEBUG_MAX_PAGE_OVERLAYS
        : vectorDebugRequest?.overlayLimit;
    if (state.vectorDebugState?.enabled === true
            && requestEnabled
            && Number.isInteger(requestedOverlayLimit)
            && requestedOverlayLimit >= 0
            && requestedOverlayLimit <= VECTOR_LAYER_DEBUG_MAX_PAGE_OVERLAYS) {
        payload.vector_layer_debug = {
            schema_version: 'vector_layer_debug_request_v1',
            include_overlays: requestedOverlayLimit > 0,
            overlay_limit: requestedOverlayLimit,
        };
    }
    return payload;
}

export const STRICT_MANUAL_STAMP_OCR_MESSAGE =
    '严格矢量模式下手绘章不做自动识别，请手动填写';

export function createStampOcrRequestGate({
    getDimensionPath,
    requestOcr,
    notify,
}) {
    let strictNoticeShown = false;
    return async function requestStampOcrIfAllowed(stamp) {
        if (!stamp || stamp.isAutoGenerated || !stamp.crop) return null;
        if (getDimensionPath?.() === 'vector_only') {
            if (!strictNoticeShown) {
                strictNoticeShown = true;
                notify?.(STRICT_MANUAL_STAMP_OCR_MESSAGE);
            }
            return null;
        }
        return requestOcr?.(stamp) ?? null;
    };
}

function _isRecord(value) {
    return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function _backendReasons(payload) {
    return Array.isArray(payload?.reasons)
        ? payload.reasons.filter(reason => typeof reason === 'string')
        : [];
}

function _analysisFailureDiagnostics(payload) {
    const candidates = [
        payload?.details,
        payload?.r33_m1_phrase_chain_audit_v1?.details,
    ];
    for (const details of candidates) {
        if (!_isRecord(details)) continue;
        const firstFailedStage = (
            typeof details.first_failed_stage === 'string'
                ? details.first_failed_stage.trim()
                : ''
        );
        if (!firstFailedStage) continue;
        const error = _isRecord(details.error) ? details.error : null;
        const errorCode = typeof error?.code === 'string'
            ? error.code.trim()
            : '';
        const detailReasons = Array.isArray(details.reasons)
            ? details.reasons.filter(
                reason => typeof reason === 'string' && reason,
            )
            : [];
        const errorReasons = Array.isArray(error?.reasons)
            ? error.reasons.filter(
                reason => typeof reason === 'string' && reason,
            )
            : [];
        return {
            firstFailedStage,
            errorCode,
            reasons: detailReasons.length > 0
                ? detailReasons
                : errorReasons,
        };
    }
    return null;
}

export class AnalysisApiError extends Error {
    constructor({ response, payload }) {
        const status = Number.isInteger(response?.status) ? response.status : null;
        const statusText = typeof response?.statusText === 'string'
            ? response.statusText.trim()
            : '';
        const backendMessage = typeof payload?.message === 'string'
            ? payload.message.trim()
            : '';
        const fallback = status === null
            ? 'Analysis request failed'
            : `HTTP ${status}${statusText ? ` ${statusText}` : ''}`;
        super(backendMessage || fallback);
        this.name = 'AnalysisApiError';
        this.code = typeof payload?.code === 'string' && payload.code
            ? payload.code
            : (status === null ? 'analysis_request_failed' : `http_${status}`);
        this.reasons = _backendReasons(payload);
        this.trace = typeof payload?.trace_id === 'string' && payload.trace_id
            ? payload.trace_id
            : null;
        this.status = status;
        this.payload = payload;
        this.recovery = typeof payload?.recovery === 'string' && payload.recovery
            ? payload.recovery
            : null;
        this.retryable = typeof payload?.retryable === 'boolean'
            ? payload.retryable
            : true;
        this.diagnostics = _analysisFailureDiagnostics(payload);
    }
}

function _formatAnalysisApiErrorAlert(error) {
    const lines = ['智能解析失败：'];
    if (error.status !== null) lines.push(`HTTP ${error.status}`);
    lines.push(`code: ${error.code}`);
    if (error.reasons.length > 0) lines.push(`reasons: ${error.reasons.join(', ')}`);
    if (error.diagnostics?.firstFailedStage) {
        lines.push(`failed_stage: ${error.diagnostics.firstFailedStage}`);
    }
    if (error.diagnostics?.errorCode) {
        lines.push(`stage_error: ${error.diagnostics.errorCode}`);
    }
    if (error.diagnostics?.reasons.length > 0) {
        lines.push(`stage_reasons: ${error.diagnostics.reasons.join(', ')}`);
    }
    if (error.trace) lines.push(`trace_id: ${error.trace}`);
    if (error.recovery === 'restart_backend_required') {
        const guidance = formatStrictRuntimeReason(error.code)
            || '需重启后端后恢复严格模式';
        lines.push(`恢复指引：${guidance}。`);
    }
    if (error.message) lines.push(`message: ${error.message}`);
    return lines.join('\n');
}

function _formatTransportErrorAlert(title, error) {
    const lines = [`${title}：`];
    if (error.status !== null) lines.push(`HTTP ${error.status}`);
    lines.push(`code: ${error.code}`);
    if (error.estimatedRequestBodyBytes !== null) {
        lines.push(`预计请求体: ${error.estimatedRequestBodyBytes} bytes`);
    }
    if (error.maxRequestBodyBytes !== null) {
        lines.push(`服务端上限: ${error.maxRequestBodyBytes} bytes`);
    }
    if (error.message) lines.push(`message: ${error.message}`);
    return lines.join('\n');
}

function _invalidResponsePayloadError(response, {
    estimatedRequestBodyBytes = null,
    maxRequestBodyBytes = null,
} = {}) {
    return new TransportError({
        code: 'invalid_response_payload',
        message: '服务端成功响应不符合预期 JSON 合同',
        status: Number.isInteger(response?.status) ? response.status : null,
        estimatedRequestBodyBytes,
        maxRequestBodyBytes,
        retryable: false,
    });
}

function _recordTransportError(entry, error) {
    entry.http_status = error.status;
    entry.code = error.code;
    entry.estimated_request_body_bytes = error.estimatedRequestBodyBytes;
    entry.max_request_body_bytes = error.maxRequestBodyBytes;
    if (
        Number.isSafeInteger(error.maxRequestBodyBytes)
        && error.maxRequestBodyBytes > 0
    ) {
        state.legacyJsonBase64MaxRequestBodyBytes = error.maxRequestBodyBytes;
    }
}

function _recordAnalyzePayload(runEntry, payload, httpStatus) {
    runEntry.http_status = httpStatus;
    if (!_isRecord(payload)) return;
    runEntry.code = typeof payload.code === 'string' ? payload.code : null;
    runEntry.recovery = typeof payload.recovery === 'string' ? payload.recovery : null;
    runEntry.reasons = _backendReasons(payload);
    runEntry.trace_id = typeof payload.trace_id === 'string' ? payload.trace_id : null;
    runEntry.debug_log = payload.debug_log || null;
    runEntry.dimensions = payload.dimensions || null;
    runEntry.basic_dimensions = payload.basic_dimensions || null;
    runEntry.references = payload.references || null;
    runEntry.view_boxes = payload.view_boxes || null;
    runEntry.review_candidates_v1 = Object.hasOwn(payload, REVIEW_CANDIDATES_ROOT_KEY)
        ? payload[REVIEW_CANDIDATES_ROOT_KEY]
        : null;
    runEntry.r33_m1_phrase_chain_audit_v1 = Object.hasOwn(
        payload,
        'r33_m1_phrase_chain_audit_v1',
    ) ? payload.r33_m1_phrase_chain_audit_v1 : null;
    runEntry.timings = payload.timings || null;
    runEntry.ocr_breakdown = payload.ocr_breakdown || null;
    runEntry.ocr_pass_counters = payload.ocr_pass_counters || null;
}

function _strictVectorOnlyAnalysisBlock(source = state) {
    if (source.recognitionSettings?.dimension_path !== 'vector_only') return null;

    const status = source.recognitionCapabilitiesStatus;
    if (status === 'idle') return null;
    if (!['loading', 'error', 'ready'].includes(status)) return null;

    const vectorOnlyRow = computeDimensionPathRowStates(
        source.strictViewSegCapability,
        source.strictTemplateCapability,
    ).find(row => row.path === 'vector_only');
    if (status === 'ready' && !vectorOnlyRow?.disabled) return null;

    return {
        status,
        error: typeof source.recognitionCapabilitiesError === 'string'
            ? source.recognitionCapabilitiesError.trim()
            : '',
        reasons: [...new Set(
            (vectorOnlyRow?.reasons || [])
                .filter(reason => typeof reason === 'string' && reason),
        )],
    };
}

function _formatStrictVectorOnlyBlockAlert(block) {
    const lines = ['严格矢量识别暂不可用，未发送分析请求。'];
    if (block.status === 'loading') {
        lines.push('能力检测仍在进行，请稍后再试。');
    } else if (block.status === 'error') {
        lines.push(`能力检测失败${block.error ? `：${block.error}` : '。'}`);
    } else {
        lines.push('严格运行资产未就绪。');
    }
    if (block.reasons.length > 0) {
        lines.push(`reasons: ${block.reasons.join(', ')}`);
    }
    const recoveryGuidance = block.reasons
        .map(formatStrictRuntimeReason)
        .find(Boolean);
    if (recoveryGuidance) lines.push(`恢复指引：${recoveryGuidance}。`);
    lines.push('请在高级设置中重试能力检测；如需继续，请手动切换到兼容识别模式。');
    return lines.join('\n');
}

// =============================================================================
// 矢量解析 + 定向 OCR（POST /analyze，单次 JSON 响应）
// =============================================================================

/**
 * 发起矢量解析请求，返回后端统一 JSON 响应对象。
 *
 * @param {number} pageIndex  1-indexed 页码
 * @param {{signal?:AbortSignal}} [options]
 * @returns {Promise<object|null>}
 *   成功：后端 JSON（含 pdf_type, dimensions, page_width, page_height 等字段）
 *   取消/普通网络失败：null；结构化 API/transport 失败：记录并抛出
 */
export async function runAnalysis(pageIndex, { signal, vectorDebugRequest } = {}) {
    if (!state.currentPdfBuffer) {
        alert('请先打开图纸文档！');
        return null;
    }

    const strictCapabilityBlock = _strictVectorOnlyAnalysisBlock();
    if (strictCapabilityBlock) {
        alert(_formatStrictVectorOnlyBlockAlert(strictCapabilityBlock));
        return null;
    }

    const controller = new AbortController();
    let timedOut = false;
    const timeoutId  = setTimeout(() => {
        timedOut = true;
        controller.abort();
    }, 300000); // CPU 模式 5 分钟上限
    const abortFromCaller = () => controller.abort();
    signal?.addEventListener('abort', abortFromCaller, { once: true });
    if (signal?.aborted) controller.abort();

    const t0 = performance.now();
    const runEntry = {
        ts: new Date().toISOString(),
        page: pageIndex,
        debug_log: null,
        dimensions: null,
        basic_dimensions: null,
        references: null,
        view_boxes: null,
        review_candidates_v1: null,
        durationMs: 0,
        ok: false,
        error: null,
        http_status: null,
        code: null,
        recovery: null,
        reasons: [],
        trace_id: null,
        estimated_request_body_bytes: null,
        max_request_body_bytes: state.legacyJsonBase64MaxRequestBodyBytes,
        r33_m1_phrase_chain_audit_v1: null,
    };

    try {
        const preparedRequest = prepareJsonBase64Body(
            state.currentPdfBuffer,
            {
                page: pageIndex,
                dpi: 200,
                settings: buildAnalyzeSettingsPayload({ vectorDebugRequest }),
            },
            state.legacyJsonBase64MaxRequestBodyBytes,
        );
        runEntry.estimated_request_body_bytes = preparedRequest.requestBodyBytes;
        const response = await fetch(ANALYZE_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    preparedRequest.body,
            signal:  controller.signal,
        });

        const result = await readResponsePayload(response);
        if (response.ok && !_isRecord(result)) {
            throw _invalidResponsePayloadError(response, {
                estimatedRequestBodyBytes: preparedRequest.requestBodyBytes,
                maxRequestBodyBytes: state.legacyJsonBase64MaxRequestBodyBytes,
            });
        }
        _recordAnalyzePayload(runEntry, result, response.status);
        updateRecognitionCapabilitiesFromPayload(result);

        if (!response.ok) {
            if ([413, 502, 504].includes(response.status)) {
                throw normalizeTransportError(response, result, {
                    estimatedRequestBodyBytes: preparedRequest.requestBodyBytes,
                    maxRequestBodyBytes: state.legacyJsonBase64MaxRequestBodyBytes,
                });
            }
            throw new AnalysisApiError({ response, payload: result });
        }

        if (result.debug_log) {
            state.lastDebugLog = result.debug_log;
        }
        if (result.dimensions) {
            state.lastDimensions = result.dimensions;
        }
        if (result.basic_dimensions) {
            state.lastBasicDimensions = result.basic_dimensions;
        }

        if (result.status !== 'success') {
            throw new AnalysisApiError({ response, payload: result });
        }
        const hasDimensions = Array.isArray(result.dimensions) && result.dimensions.length > 0;
        const hasBasicDimensions = Array.isArray(result.basic_dimensions)
            && result.basic_dimensions.length > 0;
        const hasDatumReferences = Array.isArray(result.references)
            && result.references.some(ref => ref?.type === 'datum_reference');
        const hasViewBoxes = Array.isArray(result.view_boxes)
            && result.view_boxes.length > 0;
        const hasNotes = Array.isArray(result.notes) && result.notes.length > 0;
        const hasReviewCandidatesV1 = Object.hasOwn(result, REVIEW_CANDIDATES_ROOT_KEY);
        if (!hasDimensions && !hasBasicDimensions && !hasDatumReferences
            && !hasViewBoxes && !hasNotes && !hasReviewCandidatesV1) {
            alert('智能解析未在当前页面找到可识别的尺寸标注。');
            return null;
        }

        runEntry.ok = true;
        return result;

    } catch (err) {
        runEntry.error = err.name === 'AbortError'
            ? (timedOut ? 'timeout(300s)' : 'cancelled')
            : (err.message || String(err));
        if (err.name === 'AbortError') {
            runEntry.code = timedOut ? 'client_deadline_exceeded' : 'cancelled';
        } else if (err instanceof TransportError) {
            _recordTransportError(runEntry, err);
        }
        if (err.name === 'AbortError' && timedOut) {
            alert('智能解析请求超时（300s）！请检查后端服务是否正常运行。');
        } else if (err instanceof TransportError) {
            alert(_formatTransportErrorAlert('智能解析失败', err));
        } else if (err instanceof AnalysisApiError) {
            alert(_formatAnalysisApiErrorAlert(err));
        } else if (err.name !== 'AbortError') {
            alert('智能解析失败：\n' + err.message);
        }
        if (err instanceof AnalysisApiError || err instanceof TransportError) throw err;
        return null;
    } finally {
        clearTimeout(timeoutId);
        signal?.removeEventListener('abort', abortFromCaller);
        runEntry.durationMs = Math.round(performance.now() - t0);
        pushBounded(state.analyzeRuns, runEntry, DEBUG_LOG_CAPS.analyzeRuns);
    }
}


// =============================================================================
// 手绘章定点 OCR（POST /analyze_stamp）
// 静默：失败返回 null，调用者不弹窗不打断用户
// =============================================================================

/**
 * @param {number} pageIndex  1-based 页码
 * @param {{x,y,w,h}} cropBbox  PDF 坐标系（72 DPI），左上角原点
 * @param {number} [dpi=300]    后端渲染 DPI
 * @param {string} [stampUuid]  关联的 stamp uuid（仅用于调试日志，非必需）
 * @returns {Promise<{text:string, candidates:Array}|null>}
 */
export async function runStampOCR(pageIndex, cropBbox, dpi = 300, stampUuid = null) {
    if (!state.currentPdfBuffer) return null;

    const controller = new AbortController();
    const timeoutId  = setTimeout(() => controller.abort(), 30000);  // 小区域 OCR，30s 足够

    const t0 = performance.now();
    const callEntry = {
        ts: new Date().toISOString(),
        page: pageIndex,
        cropBbox: { ...cropBbox },
        stampUuid,
        dpi,
        durationMs: 0,
        ok: false,
        response: null,
        error: null,
        code: null,
        http_status: null,
        estimated_request_body_bytes: null,
        max_request_body_bytes: state.legacyJsonBase64MaxRequestBodyBytes,
    };

    try {
        const preparedRequest = prepareJsonBase64Body(
            state.currentPdfBuffer,
            {
                page: pageIndex,
                crop_bbox: cropBbox,
                dpi,
            },
            state.legacyJsonBase64MaxRequestBodyBytes,
        );
        callEntry.estimated_request_body_bytes = preparedRequest.requestBodyBytes;
        const response = await fetch(ANALYZE_STAMP_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    preparedRequest.body,
            signal:  controller.signal,
        });
        callEntry.http_status = response.status;
        const result = await readResponsePayload(response);
        if (!response.ok) {
            throw normalizeTransportError(response, result, {
                estimatedRequestBodyBytes: preparedRequest.requestBodyBytes,
                maxRequestBodyBytes: state.legacyJsonBase64MaxRequestBodyBytes,
            });
        }
        if (!_isRecord(result)) {
            throw _invalidResponsePayloadError(response, {
                estimatedRequestBodyBytes: preparedRequest.requestBodyBytes,
                maxRequestBodyBytes: state.legacyJsonBase64MaxRequestBodyBytes,
            });
        }

        if (result.status !== 'success') {
            callEntry.error = result.message || 'status!=success';
            callEntry.response = { text: result.text || '', candidates: result.candidates || [] };
            return null;
        }
        const ret = { text: result.text || '', candidates: result.candidates || [] };
        callEntry.response = ret;
        callEntry.ok = true;
        return ret;

    } catch (err) {
        callEntry.error = err.name === 'AbortError' ? 'timeout(30s)' : (err.message || String(err));
        if (err.name === 'AbortError') {
            callEntry.code = 'client_deadline_exceeded';
        } else if (err instanceof TransportError) {
            _recordTransportError(callEntry, err);
        }
        console.warn('[runStampOCR] failed silently:', err.message || err);
        return null;
    } finally {
        clearTimeout(timeoutId);
        callEntry.durationMs = Math.round(performance.now() - t0);
        pushBounded(state.stampOcrCalls, callEntry, DEBUG_LOG_CAPS.stampOcrCalls);
    }
}


// =============================================================================
// 尺寸表 Excel 导出（POST /export）
// 返回 Blob（xlsx 二进制）；交互失败返回 null；silent 失败原样抛回事务层。
// =============================================================================

export async function runExportXlsx(pageNumber, { partNo, allPages = false, silent = false, dims = null } = {}) {
    if (!state.currentPdfBuffer) {
        if (!silent) alert('请先打开图纸文档！');
        return null;
    }

    const controller = new AbortController();
    const timeoutId  = setTimeout(() => controller.abort(), 300000);

    // dims 传值（前端校对后的 dim 列表）= 后端跳过 pipeline 直接生成 Excel；
    // null 时保留旧行为：后端重跑 pipeline。
    const requestFields = {
        page:      pageNumber,
        all_pages: allPages,
        part_no:   partNo || 'drawing',
    };
    if (dims !== null && Array.isArray(dims)) {
        requestFields.dims = dims;
    }

    const t0 = performance.now();
    const callEntry = {
        ts: new Date().toISOString(),
        page: pageNumber,
        allPages,
        partNo: requestFields.part_no,
        dimsCount: Array.isArray(dims) ? dims.length : null,
        silent,
        durationMs: 0,
        ok: false,
        error: null,
        code: null,
        http_status: null,
        estimated_request_body_bytes: null,
        max_request_body_bytes: state.legacyJsonBase64MaxRequestBodyBytes,
    };

    try {
        const preparedRequest = prepareJsonBase64Body(
            state.currentPdfBuffer,
            requestFields,
            state.legacyJsonBase64MaxRequestBodyBytes,
        );
        callEntry.estimated_request_body_bytes = preparedRequest.requestBodyBytes;
        const response = await fetch(EXPORT_URL, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    preparedRequest.body,
            signal:  controller.signal,
        });
        callEntry.http_status = response.status;

        if (!response.ok) {
            const payload = await readResponsePayload(response);
            throw normalizeTransportError(response, payload, {
                estimatedRequestBodyBytes: preparedRequest.requestBodyBytes,
                maxRequestBodyBytes: state.legacyJsonBase64MaxRequestBodyBytes,
            });
        }
        const blob = await response.blob();
        callEntry.ok = true;
        return blob;

    } catch (err) {
        callEntry.error = err.name === 'AbortError' ? 'timeout(300s)' : (err.message || String(err));
        if (err.name === 'AbortError') {
            callEntry.code = 'client_deadline_exceeded';
        } else if (err instanceof TransportError) {
            _recordTransportError(callEntry, err);
        }
        if (silent) {
            console.warn('[runExportXlsx] 失败:', err.message || err);
            throw err;
        } else if (err.name === 'AbortError') {
            alert('Excel 导出超时（300s）！请检查后端服务。');
        } else if (err instanceof TransportError) {
            alert(_formatTransportErrorAlert('Excel 导出失败', err));
        } else {
            alert('Excel 导出失败：\n' + err.message);
        }
        return null;
    } finally {
        clearTimeout(timeoutId);
        callEntry.durationMs = Math.round(performance.now() - t0);
        pushBounded(state.exportCalls, callEntry, DEBUG_LOG_CAPS.exportCalls);
    }
}


// =============================================================================
// 检验结果导入（POST /import_measurements）
// =============================================================================

export async function runImportMeasurements(files) {
    const list = Array.from(files || []);
    if (list.length === 0) {
        alert('请选择测量结果 Excel 文件。');
        return null;
    }

    const form = new FormData();
    list.forEach(file => form.append('files', file, file.name));

    try {
        const response = await fetch(IMPORT_MEASUREMENTS_URL, {
            method: 'POST',
            body: form,
        });
        const result = await response.json().catch(() => ({}));
        if (!response.ok || result.status !== 'success') {
            throw new Error(result.message || `HTTP ${response.status} ${response.statusText}`);
        }
        return result;
    } catch (err) {
        alert('测量结果导入失败：\n' + (err.message || err));
        return null;
    }
}


// =============================================================================
// 旧序号图纸导入（POST /import_legacy_stamps，无 OCR）
// =============================================================================

export async function runImportLegacyStamps(file) {
    if (!file) {
        alert('请选择旧序号 PDF。');
        return null;
    }

    const form = new FormData();
    form.append('file', file, file.name || 'legacy_stamps.pdf');

    try {
        const response = await fetch(IMPORT_LEGACY_STAMPS_URL, {
            method: 'POST',
            body: form,
        });
        const result = await response.json().catch(() => ({}));
        if (!response.ok || result.status !== 'success') {
            throw new Error(result.message || `HTTP ${response.status} ${response.statusText}`);
        }
        return result;
    } catch (err) {
        alert('旧序号图纸导入失败：\n' + (err.message || err));
        return null;
    }
}


// =============================================================================
// 后端启动日志 / 运行时统计（GET，静默失败 — 后端没起来不阻断 UI）
// =============================================================================

export async function fetchServerStartupLog() {
    try {
        const r = await fetch(STARTUP_LOG_URL, { method: 'GET' });
        if (!r.ok) return null;
        const obj = await r.json();
        obj.fetchedAt = new Date().toISOString();
        state.serverStartupLog = obj;
        return obj;
    } catch (err) {
        console.warn('[fetchServerStartupLog] 后端不可达，跳过:', err.message || err);
        return null;
    }
}

export async function fetchServerRuntimeStats() {
    try {
        const r = await fetch(RUNTIME_STATS_URL, { method: 'GET' });
        if (!r.ok) return null;
        const obj = await r.json();
        obj.fetchedAt = new Date().toISOString();
        state.serverRuntimeStats = obj;
        return obj;
    } catch (err) {
        console.warn('[fetchServerRuntimeStats] 后端不可达，跳过:', err.message || err);
        return null;
    }
}
