// app_diagnosis.js — 前端 download-log 时跑一遍 sanity-check，
// 结果嵌入 zip 的 index.json 里 `diagnosis` 段。
//
// 输入：state（含 stamps / analyzeRuns / viewBoxes 等）+ 已聚合好的 perf 对象
// 输出：纯数据对象，无 DOM / 无 fetch / 无副作用。
//
// 诊断维度（按现有发现的真实 bug 反推）：
//   tolerance_issues
//     upper_only            ─ upper_tol 非空 / lower_tol 空（可能 OCR 漏下行 或 真单边）
//     suspicious_plus_minus ─ raw_text 含 `±` 但 upper/lower 不对称（OCR 把 ± 错成 + 的嫌疑）
//     orphan_signed_token   ─ debug_log 出现 `+0.X conf>=0.95` 但没并入任何 stamp
//   capsule_issues
//     ocr_text_orphan       ─ debug_log capsule_ocr 给出文本，但没在任何 stamp aiData 中出现
//     low_gdt_final         ─ detect_gdt_frames raw_count >> final_count（双层 frame 被吃）
//   ocr_issues
//     truncated_fragments   ─ debug_log 里 reasons=['truncated_fragment'] 行汇总
//   gdt_frames              ─ {raw_count, final_count} 摘要
//   perf_warnings           ─ 单 stage avg > 5s 的告警

const RE_DEBUG_REGION_LINE = /text='([^']*)'\s+conf=([\d.]+)/;
const RE_TRUNC_FRAGMENT    = /text='([^']*)'\s+reasons=\[[^\]]*'truncated_fragment'/;
const RE_CAPSULE_OCR       = /\[capsule_ocr\].*text='([^']*)'/;
const RE_GDT_FRAMES_SUMMARY = /\[detect_gdt_frames\].*frame_candidates=(\d+).*final=(\d+)/;
const RE_DETECT_CAPSULES_PHASE3 = /\[detect_capsules\] Phase 3:.*?(\d+)\s+after filter/;

/** 主入口：返回 diagnosis 对象（始终返回，没数据时各段为空数组/null）。 */
export function buildDiagnosis(state, perf) {
    const stamps = Array.isArray(state?.stamps) ? state.stamps : [];
    const runs   = Array.isArray(state?.analyzeRuns) ? state.analyzeRuns : [];

    return {
        schema: 'pdf_reader_diagnosis_v1',
        generated_at: new Date().toISOString(),
        counts: {
            stamps: stamps.length,
            stamps_auto: stamps.filter(s => s.isAutoGenerated).length,
            stamps_confirmed: stamps.filter(s => s.confirmed).length,
            analyze_runs: runs.length,
            runs_with_debug_log: runs.filter(r => typeof r.debug_log === 'string').length,
        },
        tolerance_issues: _diagToleranceIssues(stamps, runs),
        capsule_issues:   _diagCapsuleIssues(stamps, runs),
        ocr_issues:       _diagOcrIssues(runs),
        gdt_frames:       _diagGdtFrames(runs),
        perf_warnings:    _diagPerfWarnings(perf),
    };
}

// ── tolerance ──────────────────────────────────────────────────────────────
function _diagToleranceIssues(stamps, runs) {
    const upper_only = [];
    const suspicious_plus_minus = [];

    for (const s of stamps) {
        const ai = s.aiData || {};
        const up = (ai.upper_tol || '').trim();
        const lo = (ai.lower_tol || '').trim();
        const raw = (ai._raw_text || ai.raw_text || '').trim();

        if (up && !lo) {
            upper_only.push({
                id: s.id, uuid: s.uuid,
                nominal: ai.nominal || '',
                upper_tol: up,
                raw_text: raw,
            });
            // 启发式：raw_text 里有 `±` 字符 → upper_tol 应该对称展开
            //         （后端真应只 upper 时 raw_text 通常也只 `+`）
            if (/[±]/.test(raw)) {
                suspicious_plus_minus.push({
                    id: s.id, uuid: s.uuid,
                    nominal: ai.nominal || '',
                    upper_tol: up,
                    raw_text: raw,
                    hint: 'raw_text contains ± but lower_tol empty; OCR may have misread ± as +',
                });
            }
        }
    }

    // orphan_signed_token：debug_log 中独立 `+0.X` / `-0.X` token，且 conf 高
    //   定义"独立"=region 行 text 形如 `[+\-]\d+(\.\d+)?` 整体匹配
    //   R14.5 修：absorbed 判定改字段级 + 数字边界正则，避免 +1 假阴性命中 +10/+11
    const orphan_signed_token = [];
    const RE_ORPHAN_TOKEN = /^[+\-]\d+(?:\.\d+)?$/;
    const _AI_FIELDS = ['nominal','tolerance','upper_tol','lower_tol','symbol','remarks',
                        '_raw_text','raw_text','ocr_text'];
    function _absorbedByStamps(token) {
        // 在 token 前后加非数字/非小数点边界，避免 +1 命中 +10
        const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const re = new RegExp(`(^|[^\\d.])${escaped}([^\\d.]|$)`);
        for (const s of stamps) {
            const ai = s.aiData || {};
            for (const k of _AI_FIELDS) {
                const v = ai[k];
                if (typeof v === 'string' && re.test(v)) return true;
            }
        }
        return false;
    }
    for (let i = 0; i < runs.length; i++) {
        const dl = runs[i]?.debug_log;
        if (typeof dl !== 'string') continue;
        const lines = dl.split('\n');
        for (const line of lines) {
            const m = line.match(RE_DEBUG_REGION_LINE);
            if (!m) continue;
            const text = m[1].trim();
            const conf = parseFloat(m[2]);
            if (!RE_ORPHAN_TOKEN.test(text)) continue;
            if (!Number.isFinite(conf) || conf < 0.9) continue;
            if (_absorbedByStamps(text)) continue;
            orphan_signed_token.push({
                run: i, text, conf,
                line_excerpt: line.trim().slice(0, 200),
            });
        }
    }

    return { upper_only, suspicious_plus_minus, orphan_signed_token };
}

// ── capsule ────────────────────────────────────────────────────────────────
function _diagCapsuleIssues(stamps, runs) {
    const ocr_text_orphan = [];
    let phase3_capsules = 0;

    // 收所有 stamp aiData 文本汇成单字符串供 contains 检查
    const stamp_blob = stamps.map(s => JSON.stringify(s.aiData || {})).join('\n');

    for (let i = 0; i < runs.length; i++) {
        const dl = runs[i]?.debug_log;
        if (typeof dl !== 'string') continue;
        const lines = dl.split('\n');
        for (const line of lines) {
            const mP = line.match(RE_DETECT_CAPSULES_PHASE3);
            if (mP) phase3_capsules += parseInt(mP[1], 10);

            const m = line.match(RE_CAPSULE_OCR);
            if (!m) continue;
            const text = m[1].trim();
            if (!text) continue;
            // 极短碎片（单字符 / 纯数字 1-2 位）忽略，避免噪声
            if (text.length <= 2) continue;
            // 已被任何 stamp 吸收？
            if (stamp_blob.includes(text)) continue;
            ocr_text_orphan.push({
                run: i, text,
                line_excerpt: line.trim().slice(0, 200),
            });
        }
    }

    // 双层 capsule 嫌疑：phase3_capsules / 2 > stamps_with_capsule_marker
    //   现在前端没有"该 stamp 来自 capsule"的字段，先只输出比较数据
    return {
        phase3_capsules_total: phase3_capsules,
        ocr_text_orphan,
    };
}

// ── ocr issues ──────────────────────────────────────────────────────────────
function _diagOcrIssues(runs) {
    const truncated_fragments = [];
    for (let i = 0; i < runs.length; i++) {
        const dl = runs[i]?.debug_log;
        if (typeof dl !== 'string') continue;
        const lines = dl.split('\n');
        for (const line of lines) {
            const m = line.match(RE_TRUNC_FRAGMENT);
            if (!m) continue;
            truncated_fragments.push({
                run: i,
                text: m[1],
                line_excerpt: line.trim().slice(0, 200),
            });
        }
    }
    return { truncated_fragments };
}

// ── gdt frames ──────────────────────────────────────────────────────────────
function _diagGdtFrames(runs) {
    let raw = 0, final = 0, candidates = 0, found = false;
    for (const r of runs) {
        const dl = r?.debug_log;
        if (typeof dl !== 'string') continue;
        const m = dl.match(RE_GDT_FRAMES_SUMMARY);
        if (m) {
            candidates += parseInt(m[1], 10);
            final      += parseInt(m[2], 10);
            found = true;
        }
    }
    if (!found) return null;
    return { frame_candidates: candidates, final, ratio: candidates ? +(final / candidates).toFixed(3) : null };
}

// ── perf warnings ───────────────────────────────────────────────────────────
function _diagPerfWarnings(perf) {
    if (!perf || !perf.top_stages) return [];
    const warnings = [];
    for (const s of perf.top_stages) {
        if (s.avg > 5.0) {
            warnings.push({ stage: s.stage, avg: s.avg, max: s.max, hint: 'avg > 5s' });
        }
    }
    return warnings;
}
