// js/stamp.js
// TDD 参考: 2.2.4, 3.1
import { generateUUID } from './state.js';

// ─────────────────────────────────────────────────────────────────────────────
// 2. 保留函数：计算箭头落点（手绘模式辅助，取线段与 bbox 边界的交点）
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 计算从 circleCenter 指向 box 中心的向量与 box 边界的交点
 * @param {{absX,absY}} circleCenter
 * @param {{x,y,w,h}} box
 * @returns {{absX,absY}}
 */
export function calculateArrowTip(circleCenter, box) {
    const cx = box.x + box.w / 2;
    const cy = box.y + box.h / 2;
    // 零面积 guard：bbox 退化（w 或 h ≈ 0）时，下面 (w/2)/|dx| 在 dx=0 时返回 NaN，
    // 会污染 arrowTip / routingPath / 渲染 / 导出。直接返回中心点保底
    if (box.w < 0.5 || box.h < 0.5) return { absX: cx, absY: cy };
    const dx = cx - circleCenter.absX;
    const dy = cy - circleCenter.absY;

    if (dx === 0 && dy === 0) return { absX: cx, absY: cy };

    const scaleX = (box.w / 2) / Math.abs(dx);
    const scaleY = (box.h / 2) / Math.abs(dy);
    const minScale = Math.min(scaleX, scaleY);

    return {
        absX: cx - dx * minScale,
        absY: cy - dy * minScale,
    };
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. 保留函数：初始化 crop（含 A-02 补丁）
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 根据引线方向为 Stamp 初始化 crop 裁剪框（相对 arrowTip 的偏移量）
 * A-02: 调用后若 isAutoGenerated=true，自动置 cropAdjusted=true
 * @param {Stamp} s
 */
export function initCrop(s) {
    const dx = Math.abs(s.arrowTip.absX - s.circleCenter.absX);
    const dy = Math.abs(s.arrowTip.absY - s.circleCenter.absY);
    const isV = dy > dx * 1.5;

    if (isV) {
        s.crop = { l: -30, t: 0, r: 30, b: 180 };
    } else {
        s.crop = { l: -90, t: -30, r: 90, b: 30 };
    }

    // [A-02] L1 自动生成的 Stamp crop 基于真实 bbox，视为已校准
    if (s.isAutoGenerated) s.cropAdjusted = true;
}

// ─────────────────────────────────────────────────────────────────────────────
// R14.4 B 路线：dimBbox 字段（黄框绝对坐标，跟 arrowTip 解绑）
//   背景：原架构 黄框 = arrowTip + crop offset，导致拖 arrowTip 蓝圈时黄框跟动
//   新架构：黄框位置由 s.dimBbox = {x, y, w, h} 直接给定；
//           arrowTip 由 circleCenter + dimBbox 视线交点算出（除非 arrowTipManual=true 锁住）
//   兼容：老 stamp（含 crop 但无 dimBbox）lazy 计算补齐
// ─────────────────────────────────────────────────────────────────────────────

/** Lazy 补齐 dimBbox：从 arrowTip + crop 算出黄框绝对位置（老存档迁移） */
export function ensureDimBbox(s) {
    if (s.dimBbox && s.dimBbox.w > 0 && s.dimBbox.h > 0) return;
    if (!s.arrowTip) return;
    if (!s.crop) initCrop(s);
    s.dimBbox = {
        x: s.arrowTip.absX + s.crop.l,
        y: s.arrowTip.absY + s.crop.t,
        w: s.crop.r - s.crop.l,
        h: s.crop.b - s.crop.t,
    };
}

/** 用 dimBbox 重算 arrowTip：沿 circleCenter→dimBbox 中心射线 + 8pt 外推
 *  拖章时调用，让箭头自动环绕到新视线方向 */
export function recalcArrowTipFromDimBbox(s) {
    if (!s.dimBbox || s.dimBbox.w <= 0 || s.dimBbox.h <= 0) return;
    if (!s.circleCenter) return;
    const cx = s.dimBbox.x + s.dimBbox.w / 2;
    const cy = s.dimBbox.y + s.dimBbox.h / 2;
    const rawTip = calculateArrowTip(s.circleCenter, s.dimBbox);
    const tipDx = rawTip.absX - cx;
    const tipDy = rawTip.absY - cy;
    const tipLen = Math.hypot(tipDx, tipDy) || 1;
    const ARROW_MARGIN = 8;
    s.arrowTip = {
        absX: rawTip.absX + (tipDx / tipLen) * ARROW_MARGIN,
        absY: rawTip.absY + (tipDy / tipLen) * ARROW_MARGIN,
    };
    // 同步 routingPath（如果有）
    if (s.routingPath && s.routingPath.length >= 2) {
        s.routingPath[s.routingPath.length - 1] = {
            absX: s.arrowTip.absX, absY: s.arrowTip.absY,
        };
    }
}


// ─────────────────────────────────────────────────────────────────────────────
// 6. 路由排版（AABB 碰撞 + 极坐标排序 + 引线交叉软惩罚）
// ─────────────────────────────────────────────────────────────────────────────

/**
 * AABB 碰撞检测所需的章尺寸（含 8pt 缓冲），按 fs 缩放
 * @param {number} fs 字号（默认 12；字号降级时传 11/10/9）
 */
function _stampAABB(cx, cy, idDigits, fs = 12) {
    const PAD = 8;
    const scale = fs / 16;
    const W = (idDigits <= 1 ? 44 : idDigits <= 2 ? 58 : 72) * scale;
    const H = 28 * scale;
    return { x: cx - W / 2 - PAD, y: cy - H / 2 - PAD, w: W + PAD * 2, h: H + PAD * 2 };
}

function _aabbOverlap(a, b) {
    return a.x < b.x + b.w && a.x + a.w > b.x &&
           a.y < b.y + b.h && a.y + a.h > b.y;
}

/** 叉积法线段相交判断 */
function _segmentsIntersect(p1, p2, p3, p4) {
    const d1x = p2.x - p1.x, d1y = p2.y - p1.y;
    const d2x = p4.x - p3.x, d2y = p4.y - p3.y;
    const cross = d1x * d2y - d1y * d2x;
    if (Math.abs(cross) < 1e-10) return false;
    const t = ((p3.x - p1.x) * d2y - (p3.y - p1.y) * d2x) / cross;
    const u = ((p3.x - p1.x) * d1y - (p3.y - p1.y) * d1x) / cross;
    return t > 0 && t < 1 && u > 0 && u < 1;
}

/** 线段与 AABB 是否相交（Cohen-Sutherland 简化版：四边逐一检测）*/
function _segmentAABBIntersect(p1, p2, box) {
    // 端点在 AABB 内 → 相交
    const insideP1 = p1.x >= box.x && p1.x <= box.x + box.w &&
                     p1.y >= box.y && p1.y <= box.y + box.h;
    const insideP2 = p2.x >= box.x && p2.x <= box.x + box.w &&
                     p2.y >= box.y && p2.y <= box.y + box.h;
    if (insideP1 || insideP2) return true;
    // 与 AABB 四条边做线段相交
    const bl = { x: box.x,         y: box.y };
    const br = { x: box.x + box.w, y: box.y };
    const tl = { x: box.x,         y: box.y + box.h };
    const tr = { x: box.x + box.w, y: box.y + box.h };
    return _segmentsIntersect(p1, p2, bl, br) ||
           _segmentsIntersect(p1, p2, br, tr) ||
           _segmentsIntersect(p1, p2, tr, tl) ||
           _segmentsIntersect(p1, p2, tl, bl);
}

/**
 * 为一组 mergedBoxes 生成完整 Stamp 对象数组（路由排版）
 *
 * @param {Array<{x,y,w,h}>} mergedBoxes   已合并的 bbox 列表（物理坐标系）
 * @param {number} repelCenterX  离心基准 X（cluster 几何中心）
 * @param {number} repelCenterY  离心基准 Y（cluster 几何中心）
 * @param {Array}  sharedOccupancy  跨组共享的已放置章 AABB 列表
 * @param {Array}  sharedLeaderLines 跨组共享的已有引线列表 [{x1,y1,x2,y2}]
 * @returns {Stamp[]}
 */
export function generateRoutedStamps(mergedBoxes, repelCenterX, repelCenterY,
                                      sharedOccupancy, sharedLeaderLines) {
    const finalStamps = [];
    const occupancy = sharedOccupancy || [];
    const leaderLines = sharedLeaderLines || [];
    let currentId = 1;

    // 六方向改四斜向（2/4/8/10 点）+ 字号降级 fallback
    // 方向与正上方夹角 65°（偏离 60° 整数倍，避开剖面线/倒角引线视觉重叠）
    const ANGLE_RAD = 65 * Math.PI / 180;
    const SIN = Math.sin(ANGLE_RAD);   // ≈ 0.9063
    const COS = Math.cos(ANGLE_RAD);   // ≈ 0.4226

    const ALL_DIRS = [
        { dx:  SIN, dy: -COS },  //  2 点（右上）
        { dx:  SIN, dy:  COS },  //  4 点（右下）
        { dx: -SIN, dy:  COS },  //  8 点（左下）
        { dx: -SIN, dy: -COS },  // 10 点（左上）
    ];

    // 字号降级档位：自动章默认贴近工程图尺寸字号，密集图只做小幅降级
    // 字号联动 AABB 尺寸 + 距离梯度；圆径 = fs*ratio、线宽随 fs 在 canvas_renderer.js 中联动
    const FS_LEVELS      = [12, 11, 10, 9];
    // 采用紧凑的径向排布距离，避免章体离尺寸过远。
    const BASE_DISTANCES = [30, 45, 65, 90];     // 按 fs/16 缩放
    const DIST_COSTS     = [0, 30, 80, 160];
    const PIERCE_COST    = 400;
    // 本档最优解 cost < FALLBACK_THRESHOLD 即采用；否则缩小字号重试
    const FALLBACK_THRESHOLD = PIERCE_COST;

    for (const box of mergedBoxes) {
        const bcx = box.x + box.w / 2;
        const bcy = box.y + box.h / 2;
        const idDigits = String(currentId).length;

        // 按"远离离心基准"方向排序四斜向优先级
        const dirs = [...ALL_DIRS].sort((a, b) => {
            const scoreA = a.dx * (bcx - repelCenterX) + a.dy * (bcy - repelCenterY);
            const scoreB = b.dx * (bcx - repelCenterX) + b.dy * (bcy - repelCenterY);
            return scoreB - scoreA;
        });

        let bestCx = bcx, bestCy = bcy - BASE_DISTANCES[0], bestCost = Infinity;
        let bestFs = FS_LEVELS[0];

        // 外层循环：字号降级（最多尝试 4 档）
        for (let fi = 0; fi < FS_LEVELS.length; fi++) {
            const fs = FS_LEVELS[fi];
            const scale = fs / 16;
            const distances = BASE_DISTANCES.map(d => d * scale);

            let levelCx = bcx, levelCy = bcy - distances[0], levelCost = Infinity;

            for (let di = 0; di < dirs.length; di++) {
                const dir = dirs[di];
                for (let ri = 0; ri < distances.length; ri++) {
                    const cx = bcx + dir.dx * distances[ri];
                    const cy = bcy + dir.dy * distances[ri];

                    // 硬约束：AABB 碰撞 → 跳过候选位
                    // R14.5 B1: occ._selfDim === box 表示是当前 stamp 自家 dim bbox，跳过
                    const candidate = _stampAABB(cx, cy, idDigits, fs);
                    if (occupancy.some(occ => occ._selfDim !== box && _aabbOverlap(candidate, occ))) continue;

                    // 软惩罚：引线交叉 + 穿已放气泡
                    const newLine = { x: cx, y: cy };
                    const tipPt = { x: bcx, y: bcy };
                    let crossCount = 0;
                    for (const ll of leaderLines) {
                        if (_segmentsIntersect(
                            newLine, tipPt,
                            { x: ll.x1, y: ll.y1 }, { x: ll.x2, y: ll.y2 }
                        )) crossCount++;
                    }
                    let pierceCount = 0;
                    for (const occ of occupancy) {
                        if (occ._selfDim === box) continue;  // R14.5 B1: 不算自家
                        if (_segmentAABBIntersect(newLine, tipPt, occ)) pierceCount++;
                    }

                    const cost = DIST_COSTS[ri] + crossCount * 150 + pierceCount * PIERCE_COST;
                    if (cost < levelCost) {
                        levelCost = cost;
                        levelCx = cx;
                        levelCy = cy;
                    }
                }
            }

            // 本档找到"够好"的解（不穿气泡）→ 立即采用，不再降级
            if (levelCost < FALLBACK_THRESHOLD) {
                bestCx = levelCx;
                bestCy = levelCy;
                bestCost = levelCost;
                bestFs = fs;
                break;
            }

            // 本档劣解，但优于之前档 → 记录为当前兜底（极端密集时用最小字号档）
            if (levelCost < bestCost) {
                bestCx = levelCx;
                bestCy = levelCy;
                bestCost = levelCost;
                bestFs = fs;
            }
        }

        // 注册 AABB 占位 + 引线（按最终字号）
        occupancy.push(_stampAABB(bestCx, bestCy, idDigits, bestFs));
        leaderLines.push({ x1: bestCx, y1: bestCy, x2: bcx, y2: bcy });

        const circleCenter = { absX: bestCx, absY: bestCy };
        // 计算箭头落点，然后沿方向向外退 8pt 留出呼吸空间
        const rawTip = calculateArrowTip(circleCenter, box);
        const tipDx = rawTip.absX - (box.x + box.w / 2);
        const tipDy = rawTip.absY - (box.y + box.h / 2);
        const tipLen = Math.hypot(tipDx, tipDy) || 1;
        const ARROW_MARGIN = 8;
        const arrowTip = {
            absX: rawTip.absX + (tipDx / tipLen) * ARROW_MARGIN,
            absY: rawTip.absY + (tipDy / tipLen) * ARROW_MARGIN,
        };

        finalStamps.push({
            uuid: generateUUID(),
            id: String(currentId++),
            type: 'normal',
            fs: bestFs,                     // 字号降级结果（联动圆径 & 线宽）
            ratio: 0.60,
            isAutoGenerated: true,
            circleCenter: circleCenter,
            arrowTip: arrowTip,
            crop: { l: -box.w / 2 - 4, t: -box.h / 2 - 4, r: box.w / 2 + 4, b: box.h / 2 + 4 },
            // R14.4 B 路线：dimBbox 绝对坐标，跟 arrowTip 解绑
            //   含 4pt pad，与 crop 范围一致
            dimBbox: { x: box.x - 4, y: box.y - 4, w: box.w + 8, h: box.h + 8 },
            aiData: null,
            status: 'pending',
            confirmed: false,
        });
    }

    return finalStamps;
}
