import test from 'node:test';
import assert from 'node:assert/strict';

import {
    createHistorySnapshot,
    restoreHistorySnapshot,
} from '../history_snapshot.js';

test('history snapshot restores the measurement inspection overlay without aliasing', () => {
    const source = {
        stamps: [],
        inspection: {
            active: true,
            sourceFiles: ['report.xls'],
            byStampUuid: {
                'stamp-1': { result: 'NOK', actuals: [10.12] },
            },
        },
    };
    const snapshot = createHistorySnapshot(source);

    source.inspection.byStampUuid['stamp-1'].result = 'OK';
    source.inspection.byStampUuid['stamp-1'].actuals.push(10.13);
    restoreHistorySnapshot(source, snapshot);

    assert.deepEqual(source.inspection, {
        active: true,
        sourceFiles: ['report.xls'],
        byStampUuid: {
            'stamp-1': { result: 'NOK', actuals: [10.12] },
        },
    });
    assert.notStrictEqual(source.inspection, snapshot.inspection);
});

test('history snapshot restores deleted AI stamps without aliasing', () => {
    const source = {
        stamps: [],
        deletedStamps: [{
            uuid: 'ai-deleted-1',
            isAutoGenerated: true,
            aiData: { nominal: '10', type: 'linear' },
        }],
    };
    const snapshot = createHistorySnapshot(source);

    source.deletedStamps[0].aiData.nominal = 'mutated';
    source.deletedStamps.push({ uuid: 'ai-deleted-2' });
    restoreHistorySnapshot(source, snapshot);

    assert.deepEqual(source.deletedStamps, [{
        uuid: 'ai-deleted-1',
        isAutoGenerated: true,
        aiData: { nominal: '10', type: 'linear' },
    }]);
    assert.notStrictEqual(source.deletedStamps, snapshot.deletedStamps);
});

test('legacy bare stamp-array snapshots keep their established compatibility behavior', () => {
    const target = {
        stamps: [{ uuid: 'current' }],
        deletedStamps: [{ uuid: 'feedback-queue' }],
        inspection: { active: true, sourceFiles: ['current.xls'] },
        reviewWorkspace: {
            envelopes: [{ candidate_id: 'transient' }],
            decisions: { transient: { status: 'pending' } },
            selectedCandidateId: 'transient',
        },
        viewBoxes: [{ id: 'current-view' }],
        basicDimensions: [{ id: 'current-basic' }],
        datumReferences: [{ id: 'current-datum' }],
    };

    restoreHistorySnapshot(target, [{ uuid: 'legacy-stamp' }]);

    assert.deepEqual(target.stamps, [{ uuid: 'legacy-stamp' }]);
    assert.deepEqual(target.reviewWorkspace, {
        envelopes: [], decisions: {}, selectedCandidateId: null,
    });
    assert.deepEqual(target.viewBoxes, []);
    assert.deepEqual(target.basicDimensions, []);
    assert.deepEqual(target.datumReferences, []);
    assert.deepEqual(target.deletedStamps, [{ uuid: 'feedback-queue' }]);
    assert.deepEqual(target.inspection, {
        active: true, sourceFiles: ['current.xls'],
    });
});

test('older object snapshots do not overwrite fields they cannot represent', () => {
    const target = {
        stamps: [{ uuid: 'current' }],
        deletedStamps: [{ uuid: 'current-feedback' }],
        inspection: { active: true, sourceFiles: ['current.xls'] },
    };

    restoreHistorySnapshot(target, {
        stamps: [{ uuid: 'older-object-stamp' }],
    });

    assert.deepEqual(target.stamps, [{ uuid: 'older-object-stamp' }]);
    assert.deepEqual(target.deletedStamps, [{ uuid: 'current-feedback' }]);
    assert.deepEqual(target.inspection, {
        active: true, sourceFiles: ['current.xls'],
    });
});

test('undo and redo round-trip stamps, deletion feedback, and inspection as one state', () => {
    const aiStamp = {
        uuid: 'ai-1',
        isAutoGenerated: true,
        aiData: { nominal: '10' },
    };
    const state = {
        stamps: [aiStamp],
        deletedStamps: [],
        inspection: { active: false, byStampUuid: {} },
    };
    const before = createHistorySnapshot(state);

    state.stamps = [];
    state.deletedStamps = [aiStamp];
    state.inspection = {
        active: true,
        byStampUuid: { 'ai-1': { result: 'NOK' } },
    };
    const after = createHistorySnapshot(state);

    restoreHistorySnapshot(state, before);
    assert.deepEqual(state.stamps, [aiStamp]);
    assert.deepEqual(state.deletedStamps, []);
    assert.deepEqual(state.inspection, {
        active: false, byStampUuid: {},
    });

    restoreHistorySnapshot(state, after);
    assert.deepEqual(state.stamps, []);
    assert.deepEqual(state.deletedStamps, [aiStamp]);
    assert.deepEqual(state.inspection, {
        active: true,
        byStampUuid: { 'ai-1': { result: 'NOK' } },
    });
});
