import test from 'node:test';
import assert from 'node:assert/strict';

import {
    commitReanalysisState,
    executeReanalysisTransaction,
    isUsableAnalysisResult,
} from '../reanalysis_transaction.js';
import { createHistorySnapshot, restoreHistorySnapshot } from '../history_snapshot.js';

function oldState() {
    return {
        stamps: [
            { uuid: 'ai-1', pageIndex: 1, isAutoGenerated: true },
            { uuid: 'manual-1', pageIndex: 1, isAutoGenerated: false },
            { uuid: 'ai-2', pageIndex: 2, isAutoGenerated: true },
        ],
        reviewWorkspace: {
            envelopes: [{ opaque: 'old-review-envelope' }],
            decisions: { opaque: { status: 'pending' } },
            selectedCandidateId: 'opaque',
        },
        viewBoxes: [{ id: 'vb-1', pageIndex: 1 }, { id: 'vb-2', pageIndex: 2 }],
        basicDimensions: [{ id: 'basic-1', pageIndex: 1 }, { id: 'basic-2', pageIndex: 2 }],
        datumReferences: [{ id: 'ref-1', pageIndex: 1 }, { id: 'ref-2', pageIndex: 2 }],
        clusters: [
            { clusterId: 'cluster-1', pageIndex: 1 },
            { clusterId: 'cluster-2', pageIndex: 2 },
        ],
        l1Cache: new Map([[1, ['old-dim-1']], [2, ['old-dim-2']]]),
        currentAnalyzedPages: new Set([1, 2]),
        selectedUUIDs: ['ai-1', 'manual-1', 'ai-2'],
        historyStack: [{ marker: 'old-history' }],
        historyIndex: 0,
        documentGeneration: 3,
        isAnalysisRunning: false,
    };
}

function assertCoreUnchanged(state, before, { includeHistory = true } = {}) {
    assert.deepEqual(state.stamps, before.stamps);
    assert.deepEqual(state.reviewWorkspace, before.reviewWorkspace);
    assert.deepEqual(state.viewBoxes, before.viewBoxes);
    assert.deepEqual(state.basicDimensions, before.basicDimensions);
    assert.deepEqual(state.datumReferences, before.datumReferences);
    assert.deepEqual(state.clusters, before.clusters);
    assert.deepEqual([...state.l1Cache], [...before.l1Cache]);
    assert.deepEqual([...state.currentAnalyzedPages], [...before.currentAnalyzedPages]);
    assert.deepEqual(state.selectedUUIDs, before.selectedUUIDs);
    if (includeHistory) {
        assert.deepEqual(state.historyStack, before.historyStack);
        assert.equal(state.historyIndex, before.historyIndex);
    }
}

test('timeout, HTTP error, fail-closed, and empty responses leave existing page data untouched', async () => {
    const failures = [
        async () => { throw Object.assign(new Error('timeout'), { name: 'AbortError' }); },
        async () => { throw new Error('HTTP 503'); },
        async () => ({ status: 'unsupported', dimensions: [] }),
        async () => ({ status: 'success', dimensions: [], view_boxes: [] }),
    ];

    for (const analyzePage of failures) {
        const state = oldState();
        const before = structuredClone(state);
        const result = await executeReanalysisTransaction({
            state,
            pages: [1],
            analyzePage,
            stagePage: () => { throw new Error('must not stage failed response'); },
            pushHistory: () => { throw new Error('must not write history on failure'); },
        });

        assert.equal(result.status, 'failed');
        assert.equal(result.statePreserved, true);
        assert.equal(result.pageFailures.length, 1);
        assert.equal(result.pageFailures[0].pageIndex, 1);
        assertCoreUnchanged(state, before);
        assert.equal(state.isAnalysisRunning, false);
    }
});

test('non-retryable transport failure stops the remaining page requests and preserves its code', async () => {
    const state = oldState();
    const before = structuredClone(state);
    const calls = [];
    const result = await executeReanalysisTransaction({
        state,
        pages: [1, 2, 3],
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            throw Object.assign(new Error('request exceeds whole-body limit'), {
                code: 'request_body_too_large',
                status: 413,
                retryable: false,
            });
        },
        stagePage: () => { throw new Error('must not stage transport failure'); },
        pushHistory: () => { throw new Error('must not commit transport failure'); },
    });

    assert.deepEqual(calls, [1]);
    assert.equal(result.status, 'failed');
    assert.deepEqual(result.failedPages, [1]);
    assert.deepEqual(result.skippedPages, [2, 3]);
    assert.deepEqual(result.pageFailures, [{
        pageIndex: 1,
        code: 'request_body_too_large',
        reasons: [],
        message: 'request exceeds whole-body limit',
        status: 413,
        retryable: false,
    }]);
    assertCoreUnchanged(state, before);
});

test('view-box-only strict vector shadow response cannot enter the product transaction', async () => {
    const state = oldState();
    const before = structuredClone(state);
    let stageCalls = 0;
    let historyWrites = 0;
    const result = await executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async () => ({
            status: 'success',
            dimensions: [],
            view_boxes: [{ x: 1, y: 2, w: 3, h: 4 }],
            effective_settings: { dimension_path: 'vector_only' },
            strict_yolo_view_status_v1: {
                schema_version: 'strict_yolo_view_status_v1',
                effective_backend: 'yolo',
                consumer_allowed: false,
            },
            r32_consumer_runtime_audit_v1: {
                schema_version: 'r32_consumer_runtime_audit_v1',
                call_count: 0,
                consumer_allowed_count: 0,
                consumer_allowed: false,
            },
        }),
        stagePage: () => {
            stageCalls += 1;
            return { viewBoxes: [{ id: 'shadow-vb', pageIndex: 1 }] };
        },
        pushHistory: () => { historyWrites += 1; },
    });

    assert.deepEqual(result, {
        status: 'failed',
        succeededPages: [],
        failedPages: [1],
        statePreserved: true,
        pageFailures: [{
            pageIndex: 1,
            code: 'analysis_result_not_product_eligible',
            reasons: ['strict_vector_shadow_consumer_closed'],
        }],
    });
    assert.equal(stageCalls, 0);
    assert.equal(historyWrites, 0);
    assertCoreUnchanged(state, before);
});

test('vector-only visible response without product authority fails closed', async () => {
    const state = oldState();
    const before = structuredClone(state);
    let stageCalls = 0;
    const result = await executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async () => ({
            status: 'success',
            dimensions: [{ text: 'must-not-consume' }],
            view_boxes: [{ x: 1, y: 2, w: 3, h: 4 }],
            effective_settings: { dimension_path: 'vector_only' },
        }),
        stagePage: () => {
            stageCalls += 1;
            return { stamps: [{ uuid: 'forbidden', pageIndex: 1 }] };
        },
    });

    assert.deepEqual(result.pageFailures, [{
        pageIndex: 1,
        code: 'analysis_result_not_product_eligible',
        reasons: ['strict_vector_product_authority_missing'],
    }]);
    assert.equal(result.status, 'failed');
    assert.equal(result.statePreserved, true);
    assert.equal(stageCalls, 0);
    assertCoreUnchanged(state, before);
});

test('response authority blocks closed modes without rejecting legacy or explicit product results', () => {
    const visible = {
        status: 'success',
        dimensions: [{ text: '10' }],
        view_boxes: [{ x: 1, y: 2, w: 3, h: 4 }],
    };
    const closedResults = [
        { ...visible, consumer_allowed: false },
        { ...visible, display_allowed: false },
        { ...visible, release_allowed: false },
        { ...visible, audit_only: true },
        { ...visible, result_kind: 'audit_only' },
        { ...visible, effective_mode: 'shadow' },
        {
            ...visible,
            analysis_mode_v1: {
                schema_version: 'analysis_mode_v1',
                effective_mode: 'shadow',
                consumer_allowed: false,
            },
        },
        {
            ...visible,
            analysis_mode_v1: {
                schema_version: 'analysis_mode_v1',
                effective_mode: 'unavailable',
            },
        },
        {
            ...visible,
            effective_settings: { dimension_path: 'vector_only' },
            analysis_mode_v1: {
                schema_version: 'analysis_mode_v1',
                effective_mode: 'product',
                consumer_allowed: true,
                display_allowed: true,
                release_allowed: true,
            },
            effective_mode: 'shadow',
        },
        {
            ...visible,
            effective_settings: { dimension_path: 'vector_only' },
            analysis_mode_v1: {
                schema_version: 'forged_analysis_mode',
                effective_mode: 'product',
                consumer_allowed: true,
                display_allowed: true,
                release_allowed: true,
            },
        },
        {
            ...visible,
            effective_settings: { dimension_path: 'vector_only' },
            analysis_mode_v1: {
                schema_version: 'analysis_mode_v1',
                effective_mode: 'product',
            },
        },
        {
            ...visible,
            effective_settings: { dimension_path: 'vector_only' },
            feeds_display_l3: false,
        },
    ];

    for (const result of closedResults) {
        assert.equal(isUsableAnalysisResult(result), false);
    }

    assert.equal(isUsableAnalysisResult(visible), true);
    assert.equal(isUsableAnalysisResult({ ...visible, feeds_display_l3: false }), true);
    assert.equal(isUsableAnalysisResult({
        ...visible,
        effective_settings: { dimension_path: 'vector_only' },
        strict_yolo_view_status_v1: { consumer_allowed: false },
        analysis_mode_v1: {
            schema_version: 'analysis_mode_v1',
            effective_mode: 'product',
            consumer_allowed: true,
            display_allowed: true,
            release_allowed: true,
        },
    }), true);
});

test('partial success replaces only successful-page AI data and records one undo entry', async () => {
    const state = oldState();
    let historyWrites = 0;
    const result = await executeReanalysisTransaction({
        state,
        pages: [1, 2],
        analyzePage: async pageIndex => {
            if (pageIndex === 2) throw new Error('HTTP 500');
            return { status: 'success', dimensions: [{ text: 'new-dim-1' }] };
        },
        stagePage: async (_raw, pageIndex) => ({
            stamps: [{ uuid: `new-ai-${pageIndex}`, pageIndex, isAutoGenerated: true }],
            viewBoxes: [{ id: `new-vb-${pageIndex}`, pageIndex }],
            basicDimensions: [{ id: `new-basic-${pageIndex}`, pageIndex }],
            datumReferences: [{ id: `new-ref-${pageIndex}`, pageIndex }],
            clusters: [{ clusterId: `new-cluster-${pageIndex}`, pageIndex }],
            cacheValue: [`new-dim-${pageIndex}`],
        }),
        pushHistory: () => { historyWrites += 1; },
    });

    assert.equal(result.status, 'partial');
    assert.deepEqual(result.succeededPages, [1]);
    assert.deepEqual(result.failedPages, [2]);
    assert.deepEqual(
        state.stamps.map(stamp => stamp.uuid).sort(),
        ['ai-2', 'manual-1', 'new-ai-1'],
    );
    assert.deepEqual(state.viewBoxes.map(box => box.id).sort(), ['new-vb-1', 'vb-2']);
    assert.deepEqual(state.basicDimensions.map(item => item.id).sort(), ['basic-2', 'new-basic-1']);
    assert.deepEqual(state.datumReferences.map(item => item.id).sort(), ['new-ref-1', 'ref-2']);
    assert.deepEqual(state.selectedUUIDs.sort(), ['ai-2', 'manual-1']);
    assert.deepEqual(state.l1Cache.get(1), ['new-dim-1']);
    assert.deepEqual(state.l1Cache.get(2), ['old-dim-2']);
    assert.equal(historyWrites, 1);
});

test('multi-page partial commit preserves the shadow page and reports its closed authority', async () => {
    const state = oldState();
    let stageCalls = 0;
    let historyWrites = 0;
    const result = await executeReanalysisTransaction({
        state,
        pages: [1, 2],
        analyzePage: async pageIndex => pageIndex === 1
            ? { status: 'success', dimensions: [{ text: 'new-dim-1' }] }
            : {
                status: 'success',
                dimensions: [],
                view_boxes: [{ x: 2, y: 3, w: 4, h: 5 }],
                analysis_mode_v1: {
                    schema_version: 'analysis_mode_v1',
                    effective_mode: 'shadow',
                    display_allowed: false,
                },
            },
        stagePage: async (_raw, pageIndex) => {
            stageCalls += 1;
            return {
                stamps: [{ uuid: `new-ai-${pageIndex}`, pageIndex, isAutoGenerated: true }],
                viewBoxes: [{ id: `new-vb-${pageIndex}`, pageIndex }],
                cacheValue: [`new-dim-${pageIndex}`],
            };
        },
        pushHistory: () => { historyWrites += 1; },
    });

    assert.equal(result.status, 'partial');
    assert.deepEqual(result.succeededPages, [1]);
    assert.deepEqual(result.failedPages, [2]);
    assert.deepEqual(result.pageFailures, [{
        pageIndex: 2,
        code: 'analysis_result_not_product_eligible',
        reasons: ['analysis_mode_not_product', 'analysis_mode_display_closed'],
    }]);
    assert.equal(stageCalls, 1);
    assert.equal(historyWrites, 1);
    assert.deepEqual(state.viewBoxes.map(box => box.id).sort(), ['new-vb-1', 'vb-2']);
    assert.deepEqual(state.basicDimensions.map(item => item.id), ['basic-2']);
    assert.deepEqual(state.datumReferences.map(item => item.id), ['ref-2']);
    assert.deepEqual(state.clusters.map(item => item.clusterId), ['cluster-2']);
    assert.deepEqual(state.l1Cache.get(1), ['new-dim-1']);
    assert.deepEqual(state.l1Cache.get(2), ['old-dim-2']);
    assert.deepEqual([...state.currentAnalyzedPages], [1, 2]);
    assert.ok(state.stamps.some(stamp => stamp.uuid === 'ai-2'));
    assert.ok(state.selectedUUIDs.includes('ai-2'));
});

function successfulResult(pageIndex) {
    return { status: 'success', dimensions: [{ text: String(pageIndex) }] };
}

function stagedPage(_raw, pageIndex) {
    return {
        stamps: [{ uuid: `new-ai-${pageIndex}`, pageIndex, isAutoGenerated: true }],
        cacheValue: [`new-${pageIndex}`],
    };
}

test('six-page analysis requests every page exactly once and reports exact progress', async () => {
    const state = oldState();
    const calls = [];
    const progress = [];
    const pages = Array.from({ length: 6 }, (_, index) => index + 1);
    const result = await executeReanalysisTransaction({
        state,
        pages,
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            return successfulResult(pageIndex);
        },
        stagePage: stagedPage,
        onProgress: update => progress.push(update),
    });

    assert.equal(result.status, 'success');
    assert.deepEqual(calls, pages);
    assert.deepEqual(progress.map(item => item.completed), pages);
    assert.ok(progress.every(item => item.total === 6));
});

test('fifty-page boundary has no implicit truncation', async () => {
    const state = oldState();
    const calls = [];
    const pages = Array.from({ length: 50 }, (_, index) => index + 1);
    const result = await executeReanalysisTransaction({
        state,
        pages,
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            return successfulResult(pageIndex);
        },
        stagePage: stagedPage,
    });

    assert.equal(result.status, 'success');
    assert.equal(calls.length, 50);
    assert.deepEqual(calls, pages);
});

test('cancellation discards already staged pages and leaves the snapshot untouched', async () => {
    const state = oldState();
    const before = structuredClone(state);
    const controller = new AbortController();
    const calls = [];
    let historyWrites = 0;
    const result = await executeReanalysisTransaction({
        state,
        pages: [1, 2, 3, 4, 5, 6],
        signal: controller.signal,
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            if (pageIndex === 3) controller.abort();
            return successfulResult(pageIndex);
        },
        stagePage: stagedPage,
        pushHistory: () => { historyWrites += 1; },
    });

    assert.equal(result.status, 'cancelled');
    assert.equal(result.statePreserved, true);
    assert.deepEqual(result.pageFailures, []);
    assert.deepEqual(calls, [1, 2, 3]);
    assertCoreUnchanged(state, before);
    assert.equal(historyWrites, 0);
});

test('document switch while reanalysis is deferred discards the old generation without overwriting the import', async () => {
    const state = oldState();
    let resolveAnalysis;
    const deferred = new Promise(resolve => { resolveAnalysis = resolve; });
    let stageCalls = 0;
    let historyWrites = 0;
    const transaction = executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async () => {
            await deferred;
            return successfulResult(1);
        },
        stagePage: (...args) => {
            stageCalls += 1;
            return stagedPage(...args);
        },
        pushHistory: () => { historyWrites += 1; },
    });

    assert.equal(state.isAnalysisRunning, true);
    state.stamps = [{ uuid: 'imported-doc-b', pageIndex: 1, isAutoGenerated: false }];
    state.viewBoxes = [{ id: 'imported-vb-b', pageIndex: 1 }];
    state.pageOffsets = [{ start: 0, width: 900, height: 600 }];
    state.documentGeneration += 1;
    const importedState = {
        stamps: structuredClone(state.stamps),
        viewBoxes: structuredClone(state.viewBoxes),
        pageOffsets: structuredClone(state.pageOffsets),
        documentGeneration: state.documentGeneration,
    };

    resolveAnalysis();
    const result = await transaction;

    assert.equal(result.status, 'stale');
    assert.equal(result.statePreserved, true);
    assert.equal(result.expectedDocumentGeneration, 3);
    assert.equal(result.currentDocumentGeneration, 4);
    assert.equal(stageCalls, 0);
    assert.equal(historyWrites, 0);
    assert.deepEqual(state.stamps, importedState.stamps);
    assert.deepEqual(state.viewBoxes, importedState.viewBoxes);
    assert.deepEqual(state.pageOffsets, importedState.pageOffsets);
    assert.equal(state.documentGeneration, importedState.documentGeneration);
    assert.equal(state.isAnalysisRunning, false);
});

test('reanalysis commit gate rejects a mismatched generation before writing any field', () => {
    const state = oldState();
    const before = structuredClone(state);
    const committed = commitReanalysisState(state, {
        stamps: [{ uuid: 'stale-result' }],
        viewBoxes: [{ id: 'stale-view' }],
        basicDimensions: [{ id: 'stale-basic' }],
        datumReferences: [{ id: 'stale-datum' }],
        clusters: [{ id: 'stale-cluster' }],
        selectedUUIDs: ['stale-result'],
        l1Cache: new Map([[1, ['stale']]]),
        currentAnalyzedPages: new Set([1]),
    }, state.documentGeneration - 1);

    assert.equal(committed, false);
    assertCoreUnchanged(state, before);
});

test('a concurrent trigger is rejected without issuing another page request', async () => {
    const state = oldState();
    const calls = [];
    let release;
    const pending = new Promise(resolve => { release = resolve; });
    const first = executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            await pending;
            return successfulResult(pageIndex);
        },
        stagePage: stagedPage,
    });

    const duplicate = await executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async pageIndex => {
            calls.push(pageIndex);
            return successfulResult(pageIndex);
        },
        stagePage: stagedPage,
    });
    release();
    const completed = await first;

    assert.equal(duplicate.status, 'busy');
    assert.equal(duplicate.statePreserved, true);
    assert.deepEqual(duplicate.pageFailures, []);
    assert.equal(completed.status, 'success');
    assert.deepEqual(calls, [1]);
});

test('one successful operation is one undoable history entry including cache and selection', async () => {
    const state = oldState();
    state.historyStack = [createHistorySnapshot(state)];
    state.historyIndex = 0;
    const before = structuredClone(state);

    await executeReanalysisTransaction({
        state,
        pages: [1],
        analyzePage: async () => successfulResult(1),
        stagePage: stagedPage,
        beforeCommit: () => {
            state.historyStack[state.historyIndex] = createHistorySnapshot(state);
        },
        pushHistory: () => {
            state.historyStack = state.historyStack.slice(0, state.historyIndex + 1);
            state.historyStack.push(createHistorySnapshot(state));
            state.historyIndex = state.historyStack.length - 1;
        },
    });

    assert.equal(state.historyStack.length, 2);
    assert.equal(state.historyIndex, 1);
    state.historyIndex -= 1;
    restoreHistorySnapshot(state, state.historyStack[state.historyIndex]);
    assertCoreUnchanged(state, before, { includeHistory: false });
});

test('history snapshots isolate review workspace from later mutations', () => {
    const state = oldState();
    const snapshot = createHistorySnapshot(state);

    state.reviewWorkspace.envelopes[0].opaque = 'mutated';
    state.reviewWorkspace.decisions.opaque.status = 'confirmed';
    state.reviewWorkspace.selectedCandidateId = null;

    restoreHistorySnapshot(state, snapshot);
    assert.deepEqual(state.reviewWorkspace, {
        envelopes: [{ opaque: 'old-review-envelope' }],
        decisions: { opaque: { status: 'pending' } },
        selectedCandidateId: 'opaque',
    });
});

test('restoring a legacy stamp-array snapshot clears transient review candidates', () => {
    const state = oldState();

    restoreHistorySnapshot(state, [{ uuid: 'legacy-stamp' }]);

    assert.deepEqual(state.stamps, [{ uuid: 'legacy-stamp' }]);
    assert.deepEqual(state.reviewWorkspace, {
        envelopes: [], decisions: {}, selectedCandidateId: null,
    });
});
