import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const storage = new Map();
globalThis.localStorage = {
    getItem: key => storage.get(key) ?? null,
    setItem: (key, value) => storage.set(key, String(value)),
    removeItem: key => storage.delete(key),
};

const apiClient = await import('../api_client.js');

test('manual stamp OCR gate blocks both strict call sites, notifies once, and preserves compatible modes', async () => {
    assert.equal(typeof apiClient.createStampOcrRequestGate, 'function');

    let dimensionPath = 'vector_only';
    const requests = [];
    const notices = [];
    const requestStampOCR = apiClient.createStampOcrRequestGate({
        getDimensionPath: () => dimensionPath,
        requestOcr: async stamp => {
            requests.push(stamp.uuid);
            return { text: '12.5', candidates: [] };
        },
        notify: message => notices.push(message),
    });
    const manualStamp = {
        uuid: 'manual-1',
        isAutoGenerated: false,
        crop: { l: 0, t: 0, r: 20, b: 10 },
    };

    // commitStamp and the crop-adjustment callback both call the same gated function.
    assert.equal(await requestStampOCR(manualStamp), null);
    assert.equal(await requestStampOCR(manualStamp), null);
    assert.deepEqual(requests, []);
    assert.deepEqual(notices, [
        '严格矢量模式下手绘章不做自动识别，请手动填写',
    ]);

    for (const compatibleMode of ['vector_plus_ocr', 'ocr_only']) {
        dimensionPath = compatibleMode;
        assert.deepEqual(
            await requestStampOCR(manualStamp),
            { text: '12.5', candidates: [] },
        );
    }
    assert.deepEqual(requests, ['manual-1', 'manual-1']);
    assert.equal(notices.length, 1);
});

test('manual stamp OCR gate keeps existing ineligible-stamp skips side-effect free', async () => {
    assert.equal(typeof apiClient.createStampOcrRequestGate, 'function');

    let requests = 0;
    let notices = 0;
    const requestStampOCR = apiClient.createStampOcrRequestGate({
        getDimensionPath: () => 'vector_only',
        requestOcr: async () => { requests += 1; },
        notify: () => { notices += 1; },
    });

    await requestStampOCR(null);
    await requestStampOCR({ uuid: 'auto', isAutoGenerated: true, crop: {} });
    await requestStampOCR({ uuid: 'no-crop', isAutoGenerated: false, crop: null });

    assert.equal(requests, 0);
    assert.equal(notices, 0);
});

test('commitStamp and crop adjustment are wired to the same mode-gated requester', async () => {
    const [appSource, interactionSource] = await Promise.all([
        readFile(new URL('../app.js', import.meta.url), 'utf8'),
        readFile(new URL('../app_interaction.js', import.meta.url), 'utf8'),
    ]);

    assert.match(
        appSource,
        /const _requestStampOCR = createStampOcrRequestGate\(/,
    );
    assert.match(
        appSource,
        /function commitStamp[\s\S]*?_requestStampOCR\(s\);/,
    );
    assert.match(
        appSource,
        /registerInteractionCallbacks\(commitStamp, _requestStampOCR\)/,
    );
    assert.match(
        interactionSource,
        /crop 调整结束后自动重 OCR[\s\S]*?_requestStampOCR\(s\)/,
    );
});
