// app_sidebar/popup.js — 选中章悬浮编辑窗
// 复用 _buildExpandHtml 渲染，复用 .field-* 类名 + 同样的 blur 写回逻辑。
// 模块底部副作用：注册 CustomEvent 监听 + popup mousedown / window mousemove / mouseup。

import { state } from '../state.js';
import { syncDrawLayerResolution, flashStamp, resolveIsKey } from '../canvas_renderer.js';
import { pushHistory, panTo } from '../app_utils.js';
import { syncToolbarFromSelection } from '../app_cursor.js';
import { _buildCollapseHeaderHtml } from './shared_templates.js';
import {
    _buildExpandHtml,
    _commitExpandedEdit,
    finishStampTypeChangeEditing,
    getIsEditingField, setIsEditingField,
} from './expand_form.js';
import { _showSymbolPalette, _FIELD_TO_CTX } from './symbol_palette.js';
import { updateSidebar, idSortLogic } from './list.js';

// ═══════════════════════════════════════════════════════════════════════════════
// 字段映射 + 事件绑定
// ═══════════════════════════════════════════════════════════════════════════════

const _POPUP_FIELD_MAP = {
    '.field-type': 'type', '.field-prefix': 'prefix',
    '.field-roughness': 'prefix',
    '.field-nominal': 'nominal',
    '.field-upper-tol': 'upper_tol', '.field-lower-tol': 'lower_tol',
    '.field-symbol': 'symbol',
    '.field-datum1': 'datum_1', '.field-datum2': 'datum_2', '.field-datum3': 'datum_3',
    '.field-modifier': 'modifier',
    '.field-note': 'remarks',
};

function _wireStampPopupFields(rootEl) {
    Object.entries(_POPUP_FIELD_MAP).forEach(([cls, key]) => {
        rootEl.querySelectorAll(cls).forEach(input => {
            input.addEventListener('focus', () => { setIsEditingField(true); });
            input.addEventListener('blur', e => {
                const uuid = e.target.dataset.uuid;
                const s = state.stamps.find(st => st.uuid === uuid);
                if (!s) { setIsEditingField(false); return; }
                if (!s.aiData) s.aiData = { type:'',prefix:'',nominal:'',upper_tol:'',lower_tol:'',symbol:'',datum:'',remarks:'' };
                const newVal = e.target.value;
                if (s.aiData[key] !== newVal) {
                    s.aiData[key] = newVal;
                    pushHistory();
                    syncDrawLayerResolution();
                }
                setIsEditingField(false);
            });
        });
    });
    rootEl.querySelectorAll('.field-type').forEach(sel => {
        sel.addEventListener('change', e => {
            const uuid = e.target.dataset.uuid;
            const s = state.stamps.find(st => st.uuid === uuid);
            if (!s) { setIsEditingField(false); return; }
            // updateSidebar 末尾会同步重建 popup；先解除 editing gate 才不会只重定位。
            finishStampTypeChangeEditing(s, e.target.value, updateSidebar);
        });
    });

    // ── Bug 4：popup 头部控件事件（状态点定位 / OK 确认 / × 删除 / ID 徽章切换） ──
    rootEl.querySelectorAll('.status-dot').forEach(dot => {
        dot.addEventListener('click', e => {
            const uuid = e.currentTarget.dataset.uuid;
            const s = state.stamps.find(st => st.uuid === uuid);
            if (s) { panTo(s); flashStamp(s.uuid); }
        });
    });

    rootEl.querySelectorAll('.expand-confirm-btn').forEach(btn => {
        btn.addEventListener('click', e => {
            e.stopPropagation();
            const uuid = e.currentTarget.dataset.uuid;
            // 复用 sidebar 的 sorted 计算逻辑
            const _isLowConfAi = s => (s.isAutoGenerated && !s.confirmed && s.aiData?.confidence === 'low');
            const visibleStamps = state.hideLowConfidence
                ? state.stamps.filter(s => !_isLowConfAi(s))
                : state.stamps;
            const sorted = [...visibleStamps].sort(idSortLogic);
            // P1.2：传 rootEl，让 commit 从 popup 内读字段，避免 sidebar 旧值覆盖
            _commitExpandedEdit(uuid, sorted, rootEl);
        });
    });

    rootEl.querySelectorAll('.delete-btn').forEach(btn => {
        btn.addEventListener('click', e => {
            e.stopPropagation();
            const uuid = e.currentTarget.dataset.uuid;
            const s = state.stamps.find(st => st.uuid === uuid);
            if (!s || s.confirmed) return;
            if (s.isAutoGenerated) state.deletedStamps.push(s);
            if (state.activeEditUUID === uuid) state.activeEditUUID = null;
            state.stamps = state.stamps.filter(st => st.uuid !== uuid);
            state.selectedUUIDs = state.selectedUUIDs.filter(u => u !== uuid);
            pushHistory(); updateSidebar(); syncDrawLayerResolution(); syncToolbarFromSelection();
        });
    });

    rootEl.querySelectorAll('.stamp-id-badge').forEach(badge => {
        badge.addEventListener('click', e => {
            e.stopPropagation();
            const uuid = e.currentTarget.dataset.uuid;
            const stamp = state.stamps.find(st => st.uuid === uuid);
            if (stamp) {
                const wasKey = resolveIsKey(stamp);
                stamp.isKeyOverride = !wasKey;
                stamp.type = stamp.isKeyOverride ? 'key' : 'normal';
                delete stamp._colorOverride;
                pushHistory();
                updateSidebar();
                syncDrawLayerResolution();
            }
        });
    });

    // ── Bug 2.1：popup 内的字段聚焦也弹符号面板 ──
    rootEl.querySelectorAll('.sym-palette-btn').forEach(btn => {
        btn.addEventListener('mousedown', e => {
            e.preventDefault();
        });
        btn.addEventListener('click', e => {
            e.stopPropagation();
            const symInput = btn.previousElementSibling;
            _showSymbolPalette(btn, symInput, 'symbol');
        });
    });
    for (const [fieldCls, ctxKey] of Object.entries(_FIELD_TO_CTX)) {
        rootEl.querySelectorAll(`.${fieldCls}`).forEach(input => {
            input.addEventListener('focus', () => {
                _showSymbolPalette(input, input, ctxKey);
            });
        });
    }

    // P2.3：popup 头部摘要区的 .ai-field（折叠态内联输入）也绑同款 blur+keydown
    // 与 sidebar 的 ai-field 处理逻辑一致；scope 限于 rootEl 不会双绑 sidebar
    rootEl.querySelectorAll('.ai-field').forEach(input => {
        input.addEventListener('focus', () => { setIsEditingField(true); });
        input.addEventListener('blur', (e) => {
            const uuid = e.target.dataset.uuid;
            const field = e.target.dataset.field;
            const newVal = e.target.value.trim();
            const stamp = state.stamps.find(st => st.uuid === uuid);
            if (stamp && stamp.aiData && stamp.aiData[field] !== newVal) {
                stamp.aiData[field] = newVal;
                pushHistory();
                syncDrawLayerResolution();
            }
            setIsEditingField(false);
        });
        input.addEventListener('keydown', (e) => {
            if (e.key === 'Enter') {
                e.target.blur();
            }
        });
    });
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tether 拖拽状态（popup.js 独占）
// ═══════════════════════════════════════════════════════════════════════════════

// _popupTetherOffset = { dx, dy } 相对章 screenCenter 的偏移（屏幕像素）；
// null = 用默认偏移（默认贴在章右侧）。每次切换选中章重置为 null。
let _popupTetherOffset = null;
let _lastPopupSelectedUUID = null;
let _popupDragOrigin = null;
const TETHER_RADIUS = 120;  // px — 浮窗中心相对章 center 的最大游离半径，超过则拽章

function _resolvePopupOffset(popupH, popupW, s) {
    if (_popupTetherOffset) return _popupTetherOffset;
    // D3：默认偏移采用「中心对中心」语义；popup 左缘 = 章右缘 + 20px buffer
    // dx = popupW/2 + stampRadiusScreen + 20 → popup_left = stampX + dx - popupW/2 = stampX + stampRadius + 20
    // dy = 0 → popup 中心垂直对齐章中心（避免 popup 整体跑到章上方）
    const stampRadiusPdf = (s?.fs || 16) * (s?.ratio || 0.6);
    const stampRadiusScreen = stampRadiusPdf * (state.zoom || 1);
    return {
        dx: popupW / 2 + stampRadiusScreen + 20,
        dy: 0,
    };
}

function _maybeResetPopupOffset() {
    const cur = state.selectedUUIDs.length === 1 ? state.selectedUUIDs[0] : null;
    if (cur !== _lastPopupSelectedUUID) {
        _popupTetherOffset = null;
        _lastPopupSelectedUUID = cur;
    }
}

export function updateStampPopup() {
    const popup = document.getElementById('stamp-popup');
    if (!popup) return;
    if (state.selectedUUIDs.length !== 1) {
        popup.style.display = 'none';
        _lastPopupSelectedUUID = null;
        return;
    }
    const s = state.stamps.find(st => st.uuid === state.selectedUUIDs[0]);
    if (!s) {
        popup.style.display = 'none';
        return;
    }
    _maybeResetPopupOffset();
    // 编辑中（焦点在表单内）时不重建，否则会清掉用户的输入光标
    if (getIsEditingField() && popup.contains(document.activeElement)) {
        repositionStampPopup();
        return;
    }
    // R14.3：popup 头部 = ID 徽章 / 摘要 / 删除（文字）/ OK 一行整合
    //   - withStatusDot:false 隐藏橙色定位点（D5）
    //   - deleteLabel:'删除' 替代 '×'（文字按钮更清晰）
    //   - withInlineOk:true 把 OK 拼到 header 右上角，不再渲染底部独立 confirm-row
    const headerHtml = _buildCollapseHeaderHtml(s, {
        withLocateBtn:   false,
        withStatusDot:   false,
        deleteLabel:     '删除',
        withInlineOk:    true,
        readonlySummary: true,   // R14.3.2：popup 头部 summary 是图纸翻译全览，只读
    });
    popup.innerHTML =
        `<div class="stamp-popup-header">${headerHtml}</div>` +
        _buildExpandHtml(s);
    popup.style.display = 'block';
    _wireStampPopupFields(popup);
    repositionStampPopup();
}

export function repositionStampPopup() {
    const popup = document.getElementById('stamp-popup');
    if (!popup || popup.style.display === 'none') return;
    if (state.selectedUUIDs.length !== 1) return;
    const s = state.stamps.find(st => st.uuid === state.selectedUUIDs[0]);
    if (!s) return;
    const ws = document.getElementById('workspace');
    if (!ws) return;
    const wsRect = ws.getBoundingClientRect();
    const stampX = wsRect.left + s.circleCenter.absX * state.zoom + state.panX;
    const stampY = wsRect.top  + s.circleCenter.absY * state.zoom + state.panY;
    const popupW = popup.offsetWidth || 320;
    const popupH = popup.offsetHeight || 120;
    // D3：传 popupW + s 进去，让默认偏移按「章右缘 + 20」生成中心偏移
    const off = _resolvePopupOffset(popupH, popupW, s);
    // popup 中心 = 章 center + offset (offset 是中心对中心，CSS left/top 是左上角)
    let left = stampX + off.dx - popupW / 2;
    let top  = stampY + off.dy - popupH / 2;
    // 边界 clamp（不让 popup 跑出屏幕）
    if (left < 10) left = 10;
    if (left + popupW > window.innerWidth - 10) left = window.innerWidth - popupW - 10;
    if (top < 60) top = 60;
    if (top + popupH > window.innerHeight - 10) top = window.innerHeight - popupH - 10;
    popup.style.left = left + 'px';
    popup.style.top  = top  + 'px';
}

// ── Tether 拖拽：popup 头部/边缘 mousedown 启动 ─────────────────────────────
function _onPopupMouseDown(e) {
    // 点输入/按钮/select 不触发拖（让用户能正常编辑）
    if (e.target.closest('input, select, textarea, button')) return;
    if (state.selectedUUIDs.length !== 1) return;
    const popup = document.getElementById('stamp-popup');
    if (!popup) return;
    const popupH = popup.offsetHeight || 120;
    const popupW = popup.offsetWidth || 320;
    // D3：拖拽 baseline 也走「章右缘 + 20」中心偏移，避免首帧 jump
    const sCur = state.stamps.find(st => st.uuid === state.selectedUUIDs[0]);
    const off = _resolvePopupOffset(popupH, popupW, sCur);
    // P1.1：改帧增量。lastMouseX/Y 每帧更新，originalDx/Dy 仅作首帧 baseline 兜底
    _popupDragOrigin = {
        lastMouseX: e.clientX,
        lastMouseY: e.clientY,
        originalDx: off.dx,
        originalDy: off.dy,
        stampMoved: false,
    };
    popup.classList.add('dragging');
    e.preventDefault();
}

function _onPopupMouseMove(e) {
    if (!_popupDragOrigin) return;
    // P1.1：帧增量 = 当前鼠标 - 上帧鼠标，避免 origin-based 累计折算导致的章漂移
    const incDx = e.clientX - _popupDragOrigin.lastMouseX;
    const incDy = e.clientY - _popupDragOrigin.lastMouseY;
    _popupDragOrigin.lastMouseX = e.clientX;
    _popupDragOrigin.lastMouseY = e.clientY;
    if (incDx === 0 && incDy === 0) return;

    // baseline：已有 tether offset 用它，否则用首次 mousedown 时的 originalDx/Dy
    const baseDx = _popupTetherOffset ? _popupTetherOffset.dx : _popupDragOrigin.originalDx;
    const baseDy = _popupTetherOffset ? _popupTetherOffset.dy : _popupDragOrigin.originalDy;
    let newDx = baseDx + incDx;
    let newDy = baseDy + incDy;

    // Fix 1 (P2)：tether 半径相对「拖拽起点 originalDx/Dy」算，不是相对章中心。
    // 默认偏移本身约 140-160px 已超过 TETHER_RADIUS=120，老逻辑首帧就触发 → 起手就拽章。
    // 新逻辑：用户必须从起点 baseline 向外移动 > TETHER_RADIUS 才开始折给章。
    const dragDx = newDx - _popupDragOrigin.originalDx;
    const dragDy = newDy - _popupDragOrigin.originalDy;
    const dragMag = Math.hypot(dragDx, dragDy);
    if (dragMag > TETHER_RADIUS) {
        // 超过 tether → 拽章。章移动量 = (dragMag - TETHER) 沿 drag 单位向量。
        const excess = dragMag - TETHER_RADIUS;
        const ux = dragDx / dragMag;
        const uy = dragDy / dragMag;
        const s = state.stamps.find(st => st.uuid === state.selectedUUIDs[0]);
        if (s) {
            const screenToPdf = 1 / state.zoom;
            s.circleCenter.absX += ux * excess * screenToPdf;
            s.circleCenter.absY += uy * excess * screenToPdf;
            // routingPath 头点同步 circleCenter
            if (s.routingPath && s.routingPath.length > 0) {
                s.routingPath[0].absX = s.circleCenter.absX;
                s.routingPath[0].absY = s.circleCenter.absY;
            }
            _popupDragOrigin.stampMoved = true;
        }
        // offset clamp：保持在以 originalDx/Dy 为圆心、半径 TETHER 的圆上（不是绝对原点）。
        newDx = _popupDragOrigin.originalDx + ux * TETHER_RADIUS;
        newDy = _popupDragOrigin.originalDy + uy * TETHER_RADIUS;
    }
    _popupTetherOffset = { dx: newDx, dy: newDy };
    repositionStampPopup();
    if (_popupDragOrigin.stampMoved) syncDrawLayerResolution();
}

function _onPopupMouseUp() {
    if (!_popupDragOrigin) return;
    const moved = _popupDragOrigin.stampMoved;
    const popup = document.getElementById('stamp-popup');
    if (popup) popup.classList.remove('dragging');
    _popupDragOrigin = null;
    if (moved) {
        pushHistory();
        syncDrawLayerResolution();
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// 模块副作用：CustomEvent 桥接 + DOM 事件挂载
// ═══════════════════════════════════════════════════════════════════════════════

// 监听 canvas_renderer / app_cursor 派发的事件
document.addEventListener('pdf-reader:transform-update', repositionStampPopup);
document.addEventListener('pdf-reader:selection-change', updateStampPopup);

// 拖拽：popup 上 mousedown 启动；window 上 move/up（避免鼠标飞出 popup 时丢追踪）
document.addEventListener('DOMContentLoaded', () => {
    const popup = document.getElementById('stamp-popup');
    if (popup) popup.addEventListener('mousedown', _onPopupMouseDown);
});
// 兼容已加载完的场景（DOMContentLoaded 已 fire）
{
    const popup = document.getElementById('stamp-popup');
    if (popup) popup.addEventListener('mousedown', _onPopupMouseDown);
}
window.addEventListener('mousemove', _onPopupMouseMove);
window.addEventListener('mouseup', _onPopupMouseUp);
