// app_sidebar/shared_templates.js — 折叠态行头部 + 确认行 HTML 拼装
// 被 list.js 和 popup.js 共同使用；纯 HTML 字符串生产，不绑事件。

import { escHtml } from '../app_utils.js';
import { getStampColor } from '../canvas_renderer.js';

function stampQuantity(aiData) {
    const value = aiData?.quantity ?? aiData?.Quantity;
    return Number.isInteger(value) && value >= 2 && value <= 999 ? value : 1;
}

/** 构建折叠态行头部 HTML（状态点 + ID 徽章 + 摘要 + ×）
 *  Bug 4 / Bug 5：抽出供 updateSidebar 与 updateStampPopup 复用；
 *  ⊕ 定位按钮已移除（Bug 5），由状态点本身承担 panTo。
 *
 *  D2：OK 按钮已挪出本函数，由调用方在 .stamp-confirm-row 独立行渲染。
 *  D5：新增 withStatusDot 选项；popup 头部传 false 隐藏橙色定位点。
 *  options.withLocateBtn 一律忽略，仅保留参数兼容性。
 */
export function _buildCollapseHeaderHtml(s, options = {}) {
    const {
        withStatusDot    = true,
        deleteLabel      = '×',     // R14.3：popup 传 '删除' 替代默认 '×'
        withInlineOk     = false,   // R14.3：popup 传 true 把 OK 拼进 header 右上角
        readonlySummary  = false,   // R14.3.2：popup 传 true，summary 是"图纸翻译"全览只读
    } = options;

    // 状态点颜色
    let dotColor = '#888';
    if (s.aiData && Object.values(s.aiData).some(v => v)) dotColor = '#ff9800';
    if (s.confirmed) dotColor = '#28a745';

    // 摘要串
    let summaryHtml = '';
    if (s.status === 'processing') {
        summaryHtml = '<span class="summary-processing">解析中...</span>';
    } else if (s.aiData) {
        if (readonlySummary) {
            // R14.3.2：popup 头部"图纸翻译"全览，只读 span，不允许 inline 编辑
            //   按 dim type 智能拼接：一般尺寸 / 形位公差 / 表面粗糙度 各自规则
            //   编辑统一走下面 expand form
            const text = _buildSummaryText(s);
            summaryHtml = text
                ? `<span class="summary-text summary-readonly">${escHtml(text)}</span>`
                : '<span class="summary-placeholder">待填写</span>';
        } else {
            // sidebar 行 inline 可编辑（保留原 ai-field inputs 行为）
            const nom = escHtml(s.aiData.Nominal || s.aiData.nominal || '');
            const upper = s.aiData.upper_tol || '';
            const lower = s.aiData.lower_tol || '';
            const tol = escHtml((upper && lower) ? `${upper}/${lower}` : (upper || lower));
            const sym = escHtml(s.aiData.Symbol || s.aiData.symbol || '');
            const quantity = stampQuantity(s.aiData);
            const quantityHtml = quantity > 1
                ? `<span class="ai-quantity" title="倍数">${quantity}X</span>`
                : '';
            if (nom || tol || sym || quantityHtml) {
                summaryHtml = `<span class="summary-text">` +
                    quantityHtml +
                    (nom ? `<input type="text" class="ai-field ai-nominal" value="${nom}" data-uuid="${s.uuid}" data-field="nominal" title="标称值">` : '') +
                    (tol ? `<input type="text" class="ai-field ai-tol" value="${tol}" data-uuid="${s.uuid}" data-field="tolerance" title="公差">` : '') +
                    (sym ? `<input type="text" class="ai-field ai-sym" value="${sym}" data-uuid="${s.uuid}" data-field="symbol" title="特征符号">` : '') +
                    `</span>`;
            } else {
                summaryHtml = '<span class="summary-placeholder">待填写</span>';
            }
        }
    } else {
        summaryHtml = '<span class="summary-placeholder">待识别</span>';
    }

    // [A-02] 手绘且 crop 未校准
    const cropWarnHtml = (!s.isAutoGenerated && !s.cropAdjusted)
        ? '<span class="crop-warning" title="未调整提取范围">⚠</span>' : '';

    // D5：popup 头部不需要橙色定位点（withStatusDot=false）
    const dotHtml = withStatusDot
        ? `<span class="status-dot" data-uuid="${escHtml(s.uuid)}" style="background:${dotColor};cursor:pointer" title="定位到画布"></span>`
        : '';

    // R14.3：popup 头部 inline OK 按钮（withInlineOk=true 且未确认时渲染）
    const inlineOkHtml = (withInlineOk && !s.confirmed)
        ? `<button class="expand-confirm-btn header-ok" data-uuid="${escHtml(s.uuid)}" type="button" title="确认此条">OK</button>`
        : '';

    return `
        <div class="stamp-fold-row">
            ${dotHtml}
            <span class="stamp-id-badge ${s.type}" data-uuid="${s.uuid}" style="cursor:pointer;color:${getStampColor(s)}" title="点击切换普通/重点">${escHtml(s.id)}</span>
            ${cropWarnHtml}
            <span class="stamp-summary">${summaryHtml}</span>
            <button class="delete-btn" data-uuid="${escHtml(s.uuid)}" title="删除"
                type="button" ${s.confirmed ? 'disabled' : ''}>${deleteLabel}</button>
            ${inlineOkHtml}
        </div>`;
}

/** R14.3.2：构建"图纸翻译"摘要文本（popup header 用）
 *  按 dim type 智能拼接系统理解的尺寸完整内容，忠于图纸：
 *    一般尺寸    → {prefix}{nominal} {±tol}      例: "⌀12.0 +0.1/-0.1" / "R5"
 *    形位公差    → {symbol} {tol} {datums} {mod} 例: "⊥ 0.05 A B Ⓜ"
 *    表面粗糙度  → {prefix}{nominal}             例: "Ra1.6"
 *  缺哪个就跳哪个，不渲染空段。
 */
export function _buildSummaryText(s) {
    const a = s.aiData || {};
    const type     = a.type || a.Type || '';
    const prefix   = a.prefix || a.Prefix || '';
    const nom      = a.nominal || a.Nominal || '';
    const unit     = a.unit || a.Unit || '';
    const upper    = a.upper_tol || '';
    const lower    = a.lower_tol || '';
    const sym      = a.symbol || a.Symbol || '';
    const d1       = a.datum_1 || '';
    const d2       = a.datum_2 || '';
    const d3       = a.datum_3 || '';
    const modifier = a.modifier || a.Modifier || '';
    const quantity = stampQuantity(a);

    if (type === '形位公差') {
        const datums = [d1, d2, d3].filter(Boolean).join(' ');
        // GD&T 公差值惯例落在 nominal 字段
        return [sym, nom, datums, modifier].filter(Boolean).join(' ');
    }
    if (type === '表面粗糙度') {
        return `${prefix}${nom}`.trim();
    }
    // 一般尺寸 + 兜底：[prefix][nominal] [±tol]
    // R14.5：对称公差 (+0.2 / -0.2) 合并显示为 ±0.2，忠于图纸原貌
    const withUnit = value => {
        const text = String(value || '');
        if (!text || unit !== 'degree' || text.endsWith('°')) return text;
        return `${text}°`;
    };
    let tolStr = '';
    if (upper && lower) {
        const upM = upper.match(/^\+([\d.]+)$/);
        const loM = lower.match(/^-([\d.]+)$/);
        if (upM && loM && upM[1] === loM[1]) {
            tolStr = `±${withUnit(upM[1])}`;
        } else {
            tolStr = `${withUnit(upper)}/${withUnit(lower)}`;
        }
    } else {
        tolStr = withUnit(upper || lower);
    }
    const multiplier = quantity > 1 ? `${quantity}X ` : '';
    const main = `${multiplier}${prefix}${withUnit(nom)}`.trim();
    return [main, tolStr].filter(Boolean).join(' ');
}

/** D2：构建独立 OK 行 HTML（条件由调用方决定）
 *  sidebar 仅在 isExpanded && !s.confirmed 时拼入；popup 在 !s.confirmed 时拼入。
 */
export function _buildConfirmRowHtml(s) {
    return `
        <div class="stamp-confirm-row">
            <button class="expand-confirm-btn" data-uuid="${escHtml(s.uuid)}" type="button" title="确认此条">OK</button>
        </div>`;
}
